// ui/src/lib/components/ChannelPicker.svelte
<script lang="ts">
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import { CheckmarkCircle02Icon, UserCircleIcon } from '@hugeicons/core-free-icons';
	import * as Dialog from '$lib/components/ui/dialog';
	import { Button } from '$lib/components/ui/button';
	import * as api from '$lib/api';
	import type { AccountIdentity } from '$lib/api';
	import { toast, ui } from '$lib/player.svelte';
	import { thumb } from '$lib/thumb';

	let loading = $state(false);
	let switching = $state<string | null>(null);
	let cancelling = $state(false);
	let error = $state<string | null>(null);
	let loadedForOpen = $state(false);

	$effect(() => {
		if (!ui.channelPickerOpen) {
			loadedForOpen = false;
			error = null;
			return;
		}
		if (loadedForOpen) return;
		loadedForOpen = true;
		void loadIdentities();
	});

	async function loadIdentities() {
		loading = true;
		error = null;
		try {
			ui.channelIdentities = await api.getAccountIdentities();
		} catch (e) {
			error = String(e);
		} finally {
			loading = false;
		}
	}

	async function choose(identity: AccountIdentity) {
		if (switching) return;
		switching = identity.selectionKey;
		error = null;
		try {
			const wasRequired = ui.channelPickerRequired;
			await api.switchAccount(identity.selectionKey);
			ui.channelPickerRequired = false;
			ui.channelPickerOpen = false;
			ui.channelIdentities = [];
			toast.success(wasRequired ? `Signed in as ${identity.name}` : `Switched to ${identity.name}`);
		} catch (e) {
			error = String(e);
			toast.error(error);
		} finally {
			switching = null;
		}
	}

	async function cancelSignIn() {
		if (cancelling || switching) return;
		cancelling = true;
		try {
			await api.signOut();
			ui.channelPickerRequired = false;
			ui.channelPickerOpen = false;
		} catch (e) {
			error = String(e);
		} finally {
			cancelling = false;
		}
	}

	// A new multi-channel login is intentionally unfinished until one usable identity is chosen, so
	// escape and click-outside are inert until then. Cancel sign-in is the way out.
	let dismissable: 'ignore' | 'close' = $derived(ui.channelPickerRequired ? 'ignore' : 'close');
</script>

<Dialog.Root bind:open={ui.channelPickerOpen}>
	<Dialog.Content
		class="gap-0 overflow-hidden p-0 sm:max-w-md"
		showCloseButton={!ui.channelPickerRequired}
		escapeKeydownBehavior={dismissable}
		interactOutsideBehavior={dismissable}
	>
		<div class="border-b px-5 py-4">
			<Dialog.Title class="text-lg font-semibold">Choose a YouTube channel</Dialog.Title>
			<Dialog.Description class="mt-1 text-xs text-muted-foreground">
				Library, likes and playlists will use this channel. You can switch again later.
			</Dialog.Description>
		</div>

		<div class="max-h-[26rem] min-h-32 overflow-y-auto p-2">
			{#if loading}
				<p class="px-3 py-8 text-center text-sm text-muted-foreground">Loading channels…</p>
			{:else if error}
				<div class="space-y-3 px-3 py-6 text-center">
					<p class="text-sm text-destructive">{error}</p>
					<Button variant="outline" size="sm" onclick={loadIdentities}>Try again</Button>
				</div>
			{:else if ui.channelIdentities.length === 0}
				<p class="px-3 py-8 text-center text-sm text-muted-foreground">
					YouTube did not return any selectable channels.
				</p>
			{:else}
				{#each ui.channelIdentities as identity (identity.selectionKey)}
					<button
						type="button"
						onclick={() => choose(identity)}
						disabled={switching !== null}
						class="flex w-full cursor-pointer items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors hover:bg-muted disabled:cursor-wait disabled:opacity-60"
					>
						{#if identity.thumbnail}
							<img
								src={thumb(identity.thumbnail, 96)}
								alt=""
								class="h-10 w-10 shrink-0 rounded-full object-cover ring-1 ring-border"
							/>
						{:else}
							<span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-muted">
								<HugeiconsIcon icon={UserCircleIcon} class="h-6 w-6 text-muted-foreground" />
							</span>
						{/if}
						<span class="min-w-0 flex-1">
							<span class="block truncate text-sm font-medium">{identity.name}</span>
							{#if identity.handle || identity.email}
								<span class="block truncate text-xs text-muted-foreground">
									{identity.handle ?? identity.email}
								</span>
							{/if}
						</span>
						{#if identity.selected}
							<span class="flex shrink-0 items-center gap-1 text-xs text-primary">
								<HugeiconsIcon icon={CheckmarkCircle02Icon} class="h-4 w-4" />
								Selected
							</span>
						{/if}
					</button>
				{/each}
			{/if}
		</div>

		<div class="flex justify-end border-t px-5 py-3">
			{#if ui.channelPickerRequired}
				<Button variant="outline" size="sm" onclick={cancelSignIn} disabled={cancelling || switching !== null}>
					{cancelling ? 'Cancelling…' : 'Cancel sign-in'}
				</Button>
			{:else}
				<Button variant="outline" size="sm" onclick={() => (ui.channelPickerOpen = false)}>
					Cancel
				</Button>
			{/if}
		</div>
	</Dialog.Content>
</Dialog.Root>

// frontend/src/components/ChannelPicker.tsx
import { useState, useEffect } from 'react';
import { CheckCircle2, UserCircle } from 'lucide-react';
import { Button } from './ui/Button';
import { Dialog } from './ui/Dialog';
import { AccountIdentity } from '../lib/api';
import { thumb } from '../lib/thumb';

interface ChannelPickerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  required?: boolean;
  identities: AccountIdentity[];
  onChoose: (selectionKey: string) => Promise<void>;
  onCancel?: () => Promise<void>;
  onLoad?: () => Promise<AccountIdentity[]>;
}

/**
 * Choose a YouTube channel for a multi-channel login.
 * When required=true, the dialog cannot be dismissed until a channel is chosen or sign-in is cancelled.
 */
export function ChannelPicker({
  open,
  onOpenChange,
  required = false,
  identities: initialIdentities,
  onChoose,
  onCancel,
  onLoad,
}: ChannelPickerProps) {
  const [loading, setLoading] = useState(false);
  const [switching, setSwitching] = useState<string | null>(null);
  const [cancelling, setCancelling] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [identities, setIdentities] = useState<AccountIdentity[]>(initialIdentities);
  const [loadedForOpen, setLoadedForOpen] = useState(false);

  useEffect(() => {
    if (!open) {
      setLoadedForOpen(false);
      setError(null);
      return;
    }
    if (loadedForOpen || !onLoad) return;
    setLoadedForOpen(true);
    setLoading(true);
    setError(null);
    onLoad()
      .then(setIdentities)
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }, [open, onLoad, loadedForOpen]);

  const handleChoose = async (identity: AccountIdentity) => {
    if (switching) return;
    setSwitching(identity.selectionKey);
    setError(null);
    try {
      await onChoose(identity.selectionKey);
      onOpenChange(false);
    } catch (e) {
      setError(String(e));
    } finally {
      setSwitching(null);
    }
  };

  const handleCancel = async () => {
    if (!onCancel || cancelling || switching) return;
    setCancelling(true);
    try {
      await onCancel();
      onOpenChange(false);
    } catch (e) {
      setError(String(e));
    } finally {
      setCancelling(false);
    }
  };

  const handleOpenChange = (nextOpen: boolean) => {
    if (required && !nextOpen) return; // Cannot dismiss when required
    onOpenChange(nextOpen);
  };

  return (
    <Dialog.Root open={open} onOpenChange={handleOpenChange}>
      <Dialog.Content
        className="gap-0 overflow-hidden p-0 sm:max-w-md"
        onEscapeKeyDown={(e) => required && e.preventDefault()}
        onPointerDownOutside={(e) => required && e.preventDefault()}
      >
        <div className="border-b px-5 py-4">
          <Dialog.Title className="text-lg font-semibold">Choose a YouTube channel</Dialog.Title>
          <Dialog.Description className="mt-1 text-xs text-muted-foreground">
            Library, likes and playlists will use this channel. You can switch again later.
          </Dialog.Description>
        </div>

        <div className="max-h-[26rem] min-h-32 overflow-y-auto p-2">
          {loading ? (
            <p className="px-3 py-8 text-center text-sm text-muted-foreground">Loading channels…</p>
          ) : error ? (
            <div className="space-y-3 px-3 py-6 text-center">
              <p className="text-sm text-destructive">{error}</p>
              {onLoad && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    setLoading(true);
                    setError(null);
                    onLoad()
                      .then(setIdentities)
                      .catch((e) => setError(String(e)))
                      .finally(() => setLoading(false));
                  }}
                >
                  Try again
                </Button>
              )}
            </div>
          ) : identities.length === 0 ? (
            <p className="px-3 py-8 text-center text-sm text-muted-foreground">
              YouTube did not return any selectable channels.
            </p>
          ) : (
            identities.map((identity) => (
              <button
                key={identity.selectionKey}
                type="button"
                onClick={() => handleChoose(identity)}
                disabled={switching !== null}
                className="flex w-full cursor-pointer items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors hover:bg-muted disabled:cursor-wait disabled:opacity-60"
              >
                {identity.thumbnail ? (
                  <img
                    src={thumb(identity.thumbnail, 96)}
                    alt=""
                    className="h-10 w-10 shrink-0 rounded-full object-cover ring-1 ring-border"
                  />
                ) : (
                  <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-muted">
                    <UserCircle className="h-6 w-6 text-muted-foreground" />
                  </span>
                )}
                <span className="min-w-0 flex-1">
                  <span className="block truncate text-sm font-medium">{identity.name}</span>
                  {(identity.handle || identity.email) && (
                    <span className="block truncate text-xs text-muted-foreground">
                      {identity.handle ?? identity.email}
                    </span>
                  )}
                </span>
                {identity.selected && (
                  <span className="flex shrink-0 items-center gap-1 text-xs text-primary">
                    <CheckCircle2 className="h-4 w-4" />
                    Selected
                  </span>
                )}
              </button>
            ))
          )}
        </div>

        <div className="flex justify-end border-t px-5 py-3">
          {required && onCancel ? (
            <Button variant="outline" size="sm" onClick={handleCancel} disabled={cancelling || switching !== null}>
              {cancelling ? 'Cancelling…' : 'Cancel sign-in'}
            </Button>
          ) : (
            <Button variant="outline" size="sm" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
          )}
        </div>
      </Dialog.Content>
    </Dialog.Root>
  );
}
