// ui/src/lib/components/ShareDialog.svelte
<script lang="ts">
	// "Share": the YTM link for a song/album/playlist/artist, with the artwork and title so you can
	// see what you're about to send. Opened from any ⋯ menu via `openShare`, mounted once in the
	// layout like AddToPlaylist.
	import { fade, scale } from 'svelte/transition';
	import { cubicOut } from 'svelte/easing';
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import { Cancel01Icon, Copy01Icon, Tick02Icon, Alert02Icon } from '@hugeicons/core-free-icons';
	import * as api from '$lib/api';
	import type { BrowseItem, PlaylistPage } from '$lib/api';
	import { copyText } from '$lib/clipboard';
	import { getCached, invalidateCached, putCached } from '$lib/pagecache';
	import { Switch } from '$lib/components/ui/switch';
	import { thumb } from '$lib/thumb';
	import { ui, toast } from '$lib/player.svelte';

	// Playlist browseIds carry a `VL` prefix that the watch/playlist URLs don't take.
	function shareUrl(item: BrowseItem): string {
		const id = item.id.replace(/^VL/, '');
		if (item.kind === 'song') return `https://music.youtube.com/watch?v=${id}`;
		if (item.kind === 'artist') return `https://music.youtube.com/channel/${id}`;
		// Albums only ever reach us as an `MPRE…` browseId, so link the browse page rather than the
		// `OLAK5uy_…` playlist URL YouTube's own share sheet hands out. Both resolve to the album.
		if (item.kind === 'album') return `https://music.youtube.com/browse/${id}`;
		return `https://music.youtube.com/playlist?list=${id}`;
	}

	const url = $derived(ui.share ? shareUrl(ui.share) : '');
	let copied = $state(false);

	// A private playlist's link 404s for everyone else, so the modal has to say so before the link
	// is sent. Only playlists carry a privacy setting, and only YouTube's edit header reports it,
	// which means only playlists the signed-in user owns ever resolve to anything here.
	let privacy = $state<string | undefined>(undefined);
	let owned = $state(false);
	// Keeps the toggle on screen after it has been flipped public, so the flip can be undone.
	let wasPrivate = $state(false);
	// Liked Music reports as owned but has no editable privacy (same carve-out as the playlist page).
	const canToggle = $derived(owned && ui.share?.id.replace(/^VL/, '') !== 'LM');

	$effect(() => {
		const item = ui.share;
		privacy = undefined;
		owned = false;
		wasPrivate = false;
		if (!item || item.kind !== 'playlist') return;
		const key = `playlist:${item.id}`;
		const apply = (p: PlaylistPage) => {
			// The modal may have been closed or retargeted while the fetch was in flight.
			if (ui.share?.id !== item.id) return;
			privacy = p.privacy;
			owned = p.owned;
			wasPrivate = p.privacy === 'PRIVATE';
		};
		const hit = getCached<PlaylistPage>(key);
		if (hit) return apply(hit);
		// No lighter endpoint exists: privacy rides along with the track list. The result is cached
		// under the same key the playlist page reads, so the fetch is not wasted.
		api
			.getPlaylist(item.id)
			.then((p) => {
				putCached(key, p);
				apply(p);
			})
			// A playlist we cannot read (signed out, someone else's) gets no warning: it is not
			// private, or it would not have been visible in the first place.
			.catch(() => {});
	});

	async function setPublic(next: boolean) {
		const item = ui.share;
		if (!item) return;
		const before = privacy;
		privacy = next ? 'PUBLIC' : 'PRIVATE';
		try {
			await api.editPlaylistDetails(item.id, { public: next });
			// ponytail: the playlist page keeps its own copy of `privacy` for the edit dialog, so drop
			// the cached page rather than plumbing a patch through. Worst case its Public switch reads
			// stale until the next visit, and a Save that doesn't touch it sends nothing.
			invalidateCached(`playlist:${item.id}`);
		} catch (e) {
			privacy = before;
			toast.error(String(e));
		}
	}

	function close() {
		ui.share = null;
		copied = false;
	}

	function copy() {
		copyText(url).then(
			() => {
				copied = true;
				setTimeout(() => (copied = false), 1500);
			},
			() => toast.error('Could not copy the link. Select it and press Ctrl+C.')
		);
	}
</script>

<svelte:window
	onkeydown={(e) => {
		if (ui.share && e.key === 'Escape') close();
	}}
/>

{#if ui.share}
	<div
		transition:fade={{ duration: 150 }}
		class="fixed inset-0 z-50 flex items-end justify-center bg-black/50 p-0 sm:items-center sm:p-4"
	>
		<div
			transition:scale={{ duration: 180, start: 0.96, easing: cubicOut }}
			class="max-h-[85dvh] w-full overflow-y-auto rounded-t-xl border bg-card p-4 shadow-xl sm:max-w-md sm:rounded-xl"
		>
			<div class="mb-3 flex items-start justify-between gap-3">
				<h2 class="font-heading text-base font-semibold">Share</h2>
				<button
					class="flex h-8 w-8 shrink-0 cursor-pointer items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
					onclick={close}
					aria-label="Close"
				>
					<HugeiconsIcon icon={Cancel01Icon} class="h-4 w-4" />
				</button>
			</div>

			<div class="flex items-center gap-4">
				{#if ui.share.thumbnail}
					<img
						src={thumb(ui.share.thumbnail, 400)}
						alt=""
						class="h-20 w-20 shrink-0 object-cover {ui.share.kind === 'artist'
							? 'rounded-full'
							: 'rounded-lg'}"
					/>
				{:else}
					<div class="h-20 w-20 shrink-0 rounded-lg bg-muted"></div>
				{/if}
				<div class="min-w-0">
					<div class="truncate font-medium">{ui.share.title}</div>
					{#if ui.share.subtitle}
						<div class="truncate text-sm text-muted-foreground">{ui.share.subtitle}</div>
					{/if}
				</div>
			</div>

			<div class="mt-4 flex items-center gap-2 rounded-lg border bg-muted/40 py-1 pl-3 pr-1">
				<input
					class="min-w-0 flex-1 bg-transparent py-1 text-sm text-muted-foreground outline-none"
					value={url}
					readonly
					onfocus={(e) => e.currentTarget.select()}
				/>
				<button
					class="flex h-8 shrink-0 cursor-pointer items-center gap-1.5 rounded-md px-2.5 text-sm transition-colors hover:bg-accent/10"
					onclick={copy}
					aria-label="Copy link"
				>
					<!-- icon swap via altIcon/showAlt: `icon` is frozen at mount -->
					<HugeiconsIcon icon={Copy01Icon} altIcon={Tick02Icon} showAlt={copied} class="h-4 w-4" />
					{copied ? 'Copied' : 'Copy'}
				</button>
			</div>

			{#if privacy === 'PRIVATE'}
				<div class="mt-3 flex items-start gap-2 text-xs text-amber-600 dark:text-amber-500">
					<HugeiconsIcon icon={Alert02Icon} class="mt-px h-4 w-4 shrink-0" />
					<p>This playlist is private. Anyone you send the link to will get an error.</p>
				</div>
			{/if}

			{#if wasPrivate && canToggle}
				<div class="mt-3 flex items-center justify-between gap-4 rounded-lg border px-3 py-2.5">
					<div class="min-w-0">
						<div class="text-sm font-medium">Public</div>
						<p class="text-xs text-muted-foreground">
							{privacy === 'PUBLIC'
								? 'Anyone with the link can open it.'
								: 'Turn on to make the link work for everyone.'}
						</p>
					</div>
					<Switch
						checked={privacy === 'PUBLIC'}
						onCheckedChange={setPublic}
						aria-label="Public playlist"
					/>
				</div>
			{/if}
		</div>
	</div>
{/if}

// frontend/src/components/ShareDialog.tsx
import { useState, useEffect } from 'react';
import { Button } from './ui/Button';
import { X, Copy, Check, AlertCircle } from 'lucide-react';
import { Switch } from './ui/Switch';
import { thumb } from '../lib/thumb';
import { BrowseItem } from '../lib/api';
import { copyText } from '../lib/clipboard';
import * as api from '../lib/api';

interface ShareDialogProps {
  item: BrowseItem | null;
  onClose: () => void;
}

export function ShareDialog({ item, onClose }: ShareDialogProps) {
  const [copied, setCopied] = useState(false);
  const [privacy, setPrivacy] = useState<string | undefined>(undefined);
  const [owned, setOwned] = useState(false);
  const [wasPrivate, setWasPrivate] = useState(false);

  // Playlist browseIds carry a `VL` prefix that the watch/playlist URLs don't take.
  const getShareUrl = (item: BrowseItem): string => {
    const id = item.id.replace(/^VL/, '');
    if (item.kind === 'song') return `https://music.youtube.com/watch?v=${id}`;
    if (item.kind === 'artist') return `https://music.youtube.com/channel/${id}`;
    // Albums only ever reach us as an `MPRE…` browseId, so link the browse page rather than the
    // `OLAK5uy_…` playlist URL YouTube's own share sheet hands out. Both resolve to the album.
    if (item.kind === 'album') return `https://music.youtube.com/browse/${id}`;
    return `https://music.youtube.com/playlist?list=${id}`;
  };

  const url = item ? getShareUrl(item) : '';
  const canToggle = owned && item?.id.replace(/^VL/, '') !== 'LM'; // Liked Music has no editable privacy

  useEffect(() => {
    setPrivacy(undefined);
    setOwned(false);
    setWasPrivate(false);
    setCopied(false);

    if (!item || item.kind !== 'playlist') return;

    // Fetch playlist details to get privacy status
    api
      .getPlaylist(item.id)
      .then((playlist) => {
        if (item.id !== item.id) return; // Dialog retargeted - we don't have playlist.id, so checking item
        setPrivacy(playlist.privacy);
        setOwned(playlist.owned || false);
        setWasPrivate(playlist.privacy === 'PRIVATE');
      })
      .catch(() => {
        // Can't read = not private or not accessible
      });
  }, [item]);

  const handleCopy = async () => {
    try {
      await copyText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Show error toast if available
      console.error('Could not copy the link');
    }
  };

  const handleSetPublic = async (isPublic: boolean) => {
    if (!item) return;
    const before = privacy;
    setPrivacy(isPublic ? 'PUBLIC' : 'PRIVATE');
    try {
      await api.editPlaylistDetails(item.id, { public: isPublic });
    } catch (e) {
      setPrivacy(before);
      console.error(e);
    }
  };

  if (!item) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 p-0 sm:items-center sm:p-4"
      onClick={onClose}
    >
      <div
        className="max-h-[85dvh] w-full overflow-y-auto rounded-t-xl border bg-card p-4 shadow-xl sm:max-w-md sm:rounded-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="mb-3 flex items-start justify-between gap-3">
          <h2 className="font-heading text-base font-semibold">Share</h2>
          <button
            className="flex h-8 w-8 shrink-0 cursor-pointer items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
            onClick={onClose}
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="flex items-center gap-4">
          {item.thumbnail ? (
            <img
              src={thumb(item.thumbnail, 400)}
              alt=""
              className={`h-20 w-20 shrink-0 object-cover ${
                item.kind === 'artist' ? 'rounded-full' : 'rounded-lg'
              }`}
            />
          ) : (
            <div className="h-20 w-20 shrink-0 rounded-lg bg-muted"></div>
          )}
          <div className="min-w-0">
            <div className="truncate font-medium">{item.title}</div>
            {item.subtitle && (
              <div className="truncate text-sm text-muted-foreground">{item.subtitle}</div>
            )}
          </div>
        </div>

        <div className="mt-4 flex items-center gap-2 rounded-lg border bg-muted/40 py-1 pl-3 pr-1">
          <input
            className="min-w-0 flex-1 bg-transparent py-1 text-sm text-muted-foreground outline-none"
            value={url}
            readOnly
            onFocus={(e) => e.currentTarget.select()}
          />
          <button
            className="flex h-8 shrink-0 cursor-pointer items-center gap-1.5 rounded-md px-2.5 text-sm transition-colors hover:bg-accent/10"
            onClick={handleCopy}
            aria-label="Copy link"
          >
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>

        {privacy === 'PRIVATE' && (
          <div className="mt-3 flex items-start gap-2 text-xs text-amber-600 dark:text-amber-500">
            <AlertCircle className="mt-px h-4 w-4 shrink-0" />
            <p>This playlist is private. Anyone you send the link to will get an error.</p>
          </div>
        )}

        {wasPrivate && canToggle && (
          <div className="mt-3 flex items-center justify-between gap-4 rounded-lg border px-3 py-2.5">
            <div className="min-w-0">
              <div className="text-sm font-medium">Public</div>
              <p className="text-xs text-muted-foreground">
                {privacy === 'PUBLIC'
                  ? 'Anyone with the link can open it.'
                  : 'Turn on to make the link work for everyone.'}
              </p>
            </div>
            <Switch
              checked={privacy === 'PUBLIC'}
              onCheckedChange={handleSetPublic}
              aria-label="Public playlist"
            />
          </div>
        )}
      </div>
    </div>
  );
}
