// ui/src/lib/components/TrackRowSkeleton.svelte
<script lang="ts">
	import { Skeleton } from '$lib/components/ui/skeleton';

	// Mirrors TrackRow's layout for loading track lists.
	let { hideThumb = false }: { hideThumb?: boolean } = $props();
</script>

<div class="flex w-full items-center gap-3 p-2">
	{#if !hideThumb}
		<Skeleton class="h-10 w-10 shrink-0 rounded-md" />
	{/if}
	<div class="min-w-0 flex-1 space-y-1.5">
		<Skeleton class="h-3.5 w-1/3 rounded" />
		<Skeleton class="h-3 w-1/5 rounded" />
	</div>
	<Skeleton class="h-3 w-8 shrink-0 rounded" />
</div>

// frontend/src/components/TrackRowSkeleton.tsx
import React from 'react';
import { Skeleton } from './ui/Skeleton';

export const TrackRowSkeleton: React.FC = () => (
  <div className="flex items-center gap-3 px-2 py-1.5">
    <Skeleton className="h-10 w-10 rounded" />
    <div className="flex-1 space-y-1.5">
      <Skeleton className="h-3.5 w-3/5 rounded" />
      <Skeleton className="h-3 w-2/5 rounded" />
    </div>
    <Skeleton className="h-3 w-8 rounded" />
  </div>
);
