// ui/src/routes/search-more/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import TrackRow from '$lib/components/TrackRow.svelte';
	import TrackRowSkeleton from '$lib/components/TrackRowSkeleton.svelte';
	import MediaCard from '$lib/components/MediaCard.svelte';
	import MediaCardSkeleton from '$lib/components/MediaCardSkeleton.svelte';
	import ErrorState from '$lib/components/ErrorState.svelte';
	import * as api from '$lib/api';
	import type { BrowseItem, SongItem } from '$lib/api';
	import { openAddToPlaylist, playSong } from '$lib/player.svelte';
	import { getCached, putCached } from '$lib/pagecache';

	type MoreResult = { songs: SongItem[]; cards: BrowseItem[] };

	let songs = $state<SongItem[]>([]);
	let cards = $state<BrowseItem[]>([]);
	let loading = $state(true);
	let error = $state<string | null>(null);

	const q = $derived(page.url.searchParams.get('q') ?? '');
	const cat = $derived(page.url.searchParams.get('cat') ?? 'songs');
	const label = $derived({ songs: 'Songs', albums: 'Albums', artists: 'Artists', playlists: 'Playlists' }[cat] ?? 'Results');

	async function load(query: string, category: string) {
		const key = `searchmore:${category}:${query}`;
		const hit = getCached<MoreResult>(key);
		if (hit) {
			songs = hit.songs;
			cards = hit.cards;
			loading = false;
		} else {
			loading = true;
			songs = [];
			cards = [];
		}
		error = null;
		try {
			let fresh: MoreResult;
			if (category === 'songs') {
				fresh = { songs: await api.search(query), cards: [] };
			} else {
				fresh = {
					songs: [],
					cards: await api.searchCards(query, category as 'albums' | 'artists' | 'playlists')
				};
			}
			if (query !== q || category !== cat) return; // superseded by navigation
			songs = fresh.songs;
			cards = fresh.cards;
			putCached(key, fresh);
		} catch (e) {
			if (query !== q || category !== cat) return;
			if (!hit) error = String(e);
		} finally {
			if (query === q && category === cat) loading = false;
		}
	}

	$effect(() => {
		if (q) load(q, cat);
	});
</script>

<div class="p-6">
	<h1 class="mb-1 font-heading text-2xl font-bold">{label}</h1>
	<p class="mb-6 text-sm text-muted-foreground">Results for “{q}”</p>

	{#if loading}
		{#if cat === 'songs'}
			{#each Array(10) as _, i (i)}
				<TrackRowSkeleton />
			{/each}
		{:else}
			<div class="card-grid">
				{#each Array(12) as _, i (i)}
					<MediaCardSkeleton />
				{/each}
			</div>
		{/if}
	{:else if error}
		<ErrorState message={error} onRetry={() => load(q, cat)} />
	{:else if cat === 'songs'}
		<div class="content-in">
			{#each songs as song (song.video_id)}
				<TrackRow
					{song}
					showPlayCount
					onplay={() => playSong(song)}
					onAdd={() => openAddToPlaylist(song)}
				/>
			{:else}
				<p class="text-sm text-muted-foreground">Nothing found.</p>
			{/each}
		</div>
	{:else if cards.length}
		<div class="card-grid content-in">
			{#each cards as item (item.id + item.title)}
				<MediaCard {item} />
			{/each}
		</div>
	{:else}
		<p class="text-sm text-muted-foreground">Nothing found.</p>
	{/if}
</div>

// frontend/src/features/search/SearchMore.tsx
import React, { useState, useEffect } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { TrackRow } from '../../components/TrackRow';
import { Shelf } from '../../components/Shelf';
import { MediaCardSkeleton } from '../../components/MediaCardSkeleton';
import { TrackRowSkeleton } from '../../components/TrackRowSkeleton';
import { Skeleton } from '../../components/ui/Skeleton';
import { ErrorState } from '../../components/ui/ErrorState';
import type { BrowseItem, SongItem } from '../../lib/api';
import * as api from '../../lib/api';

type Cat = 'songs' | 'albums' | 'artists' | 'playlists';

export const SearchMore: React.FC = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const q = searchParams.get('q') ?? '';
  const cat = (searchParams.get('cat') ?? 'songs') as Cat;

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [songs, setSongs] = useState<SongItem[]>([]);
  const [cards, setCards] = useState<BrowseItem[]>([]);

  useEffect(() => {
    if (!q) return;
    setLoading(true);
    (cat === 'songs'
      ? api.search(q).then((res) => { setSongs(res); })
      : api.searchCards(q, cat as 'albums' | 'artists' | 'playlists').then((res) => { setCards(res); })
    )
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }, [q, cat]);

  return (
    <div className="page-scroll">
      <div className="border-b px-4 py-4">
        <button className="mb-2 text-xs text-muted-foreground hover:text-foreground" onClick={() => navigate(-1)}>← Back</button>
        <h1 className="text-xl font-bold capitalize">{cat} for "{q}"</h1>
      </div>
      <div className="px-4 py-4">
        {loading ? (
          <div className="flex flex-col gap-2">
            {[0,1,2,3,4,5].map((i) => cat === 'songs' ? <TrackRowSkeleton key={i} /> : (
              <div key={i} className="w-36 shrink-0"><MediaCardSkeleton /></div>
            ))}
          </div>
        ) : error ? (
          <ErrorState message={error} />
        ) : cat === 'songs' ? (
          songs.map((song, i) => <TrackRow key={song.video_id} song={song} index={i} showPlayCount onplay={() => {}} />)
        ) : (
          <div className="card-grid">
            {cards.map((item) => (
              <div key={item.id}><MediaCardSkeleton /></div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
