// frontend/src/components/AddToPlaylist.tsx
import React, { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import type { BrowseItem, SongItem } from '../lib/api';
import * as api from '../lib/api';
import { cn } from '../lib/utils';

interface Props {
  songs: SongItem[] | null;
  onClose: () => void;
}

export const AddToPlaylist: React.FC<Props> = ({ songs, onClose }) => {
  const [playlists, setPlaylists] = useState<BrowseItem[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!songs) return;
    setLoading(true);
    api.getLibrary()
      .then((p) => setPlaylists(p.filter((i) => i.id !== api.ON_REPEAT_ID)))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [songs]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [onClose]);

  if (!songs) return null;

  async function pick(pl: BrowseItem) {
    const s = songs;
    onClose();
    if (!s?.length) return;
    try {
      for (const song of s) {
        await api.addToPlaylist(pl.id, song.video_id);
      }
    } catch (e) {
      console.error('Add to playlist error:', e);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 sm:items-center sm:p-4">
      <div className="max-h-[85dvh] w-full overflow-y-auto rounded-t-xl border bg-card p-4 shadow-xl sm:max-w-sm sm:rounded-xl">
        <div className="mb-3 flex items-center justify-between">
          <h2 className="font-heading text-base font-semibold">Add to playlist</h2>
          <button
            className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
            onClick={onClose}
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
        {loading ? (
          <p className="p-2 text-sm text-muted-foreground">Loading…</p>
        ) : playlists.length ? (
          <div className="max-h-80 overflow-y-auto">
            {playlists.map((pl) => (
              <button
                key={pl.id}
                className="flex w-full items-center gap-3 rounded-lg p-2 text-left hover:bg-accent/10"
                onClick={() => pick(pl)}
              >
                {pl.thumbnail ? (
                  <img src={pl.thumbnail} alt="" className="h-10 w-10 rounded-md object-cover" />
                ) : (
                  <div className="h-10 w-10 rounded-md bg-muted" />
                )}
                <div className="min-w-0">
                  <div className="truncate text-sm font-medium">{pl.title}</div>
                  {pl.subtitle && <div className="truncate text-xs text-muted-foreground">{pl.subtitle}</div>}
                </div>
              </button>
            ))}
          </div>
        ) : (
          <p className="p-2 text-sm text-muted-foreground">No playlists yet — create one in your Library.</p>
        )}
      </div>
    </div>
  );
};

// ui/src/lib/components/AddToPlaylist.svelte
<script lang="ts">
	import { fade, scale } from 'svelte/transition';
	import { cubicOut } from 'svelte/easing';
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import { Cancel01Icon } from '@hugeicons/core-free-icons';
	import * as api from '$lib/api';
	import type { BrowseItem } from '$lib/api';
	import {
		ui,
		toast,
		bumpLibraryTrackCount,
		notePlaylistAdd,
		noteSavedIn
	} from '$lib/player.svelte';

	let playlists = $state<BrowseItem[]>([]);
	let loading = $state(false);

	// Fetch the library playlists fresh each time the picker opens (cheap; picks up new playlists).
	// On Repeat is dropped: it's built from local play counts, so there is nothing to add a song to.
	// The command boundary refuses it too, but a target you can tap and can't use is the bug.
	$effect(() => {
		if (ui.addSongs) {
			loading = true;
			api
				.getLibrary()
				.then((p) => (playlists = p.filter((i) => i.id !== api.ON_REPEAT_ID)))
				.catch((e) => toast.error(String(e)))
				.finally(() => (loading = false));
		}
	});

	function close() {
		ui.addSongs = null;
	}

	async function pick(pl: BrowseItem) {
		const songs = ui.addSongs;
		close();
		if (!songs?.length) return;
		try {
			// Sequential — a whole album is a handful of requests; don't hammer the API in parallel.
			// YouTube refuses a track the playlist already holds, so only the ones it accepted get
			// counted and drawn: an optimistic row for a refused add is a row that can never be
			// removed (no setVideoId behind it) until the app restarts.
			const added: typeof songs = [];
			for (const song of songs) {
				if (await api.addToPlaylist(pl.id, song.video_id)) added.push(song);
			}
			const dupes = songs.length - added.length;
			// Every song, not just the accepted ones: a refusal means the playlist already holds it,
			// so its "saved" mark is right either way.
			noteSavedIn(pl.id, songs.map((s) => s.video_id));
			if (added.length) {
				bumpLibraryTrackCount(pl.id, added.length);
				notePlaylistAdd(pl.id, added);
			}
			if (!added.length) {
				toast(dupes > 1 ? `All ${dupes} are already in ${pl.title}` : `Already in ${pl.title}`);
			} else if (dupes) {
				toast.success(`Added ${added.length} to ${pl.title} (${dupes} already there)`);
			} else {
				toast.success(
					added.length > 1 ? `Added ${added.length} songs to ${pl.title}` : `Added to ${pl.title}`
				);
			}
		} catch (e) {
			toast.error(String(e));
		}
	}
</script>

<svelte:window
	onkeydown={(e) => {
		if (ui.addSongs && e.key === 'Escape') close();
	}}
/>

{#if ui.addSongs}
	<div
		transition:fade={{ duration: 150 }}
		class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
	>
		<div
			transition:scale={{ duration: 180, start: 0.96, easing: cubicOut }}
			class="w-full max-w-sm rounded-xl border bg-card p-4 shadow-xl"
		>
			<div class="mb-3 flex items-center justify-between">
				<h2 class="font-heading text-base font-semibold">Add to playlist</h2>
				<button
					class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
					onclick={close}
					aria-label="Close"
				>
					<HugeiconsIcon icon={Cancel01Icon} class="h-4 w-4" />
				</button>
			</div>
			{#if loading}
				<p class="p-2 text-sm text-muted-foreground">Loading…</p>
			{:else if playlists.length}
				<div class="max-h-80 overflow-y-auto">
					{#each playlists as pl (pl.id)}
						<button
							class="flex w-full items-center gap-3 rounded-lg p-2 text-left hover:bg-accent/10"
							onclick={() => pick(pl)}
						>
							{#if pl.thumbnail}
								<img src={pl.thumbnail} alt="" class="h-10 w-10 rounded-md object-cover" />
							{:else}
								<div class="h-10 w-10 rounded-md bg-muted"></div>
							{/if}
							<div class="min-w-0">
								<div class="truncate text-sm font-medium">{pl.title}</div>
								{#if pl.subtitle}
									<div class="truncate text-xs text-muted-foreground">{pl.subtitle}</div>
								{/if}
							</div>
						</button>
					{/each}
				</div>
			{:else}
				<p class="p-2 text-sm text-muted-foreground">
					No playlists yet — create one in your Library.
				</p>
			{/if}
		</div>
	</div>
{/if}
