// frontend/src/components/ColorPicker.tsx
import React, { useState, useEffect, useRef } from 'react';
import { cn } from '../lib/utils';
import { hexToHsv, hsvToHex } from '../lib/color';

interface Props {
  value: string;
  onChange: (hex: string) => void;
}

export const ColorPicker: React.FC<Props> = ({ value, onChange }) => {
  const [hsv, setHsv] = useState(() => hexToHsv(value));
  const [text, setText] = useState(value);
  const svRef = useRef<HTMLDivElement>(null);
  const hRef = useRef<HTMLDivElement>(null);
  const draggingSV = useRef(false);
  const draggingH = useRef(false);

  useEffect(() => {
    const h = hexToHsv(value);
    setHsv(h);
    setText(value);
  }, [value]);

  function commit(h: number, s: number, v: number) {
    const hex = hsvToHex(h, s, v);
    setText(hex);
    onChange(hex);
  }

  function svPointer(e: React.PointerEvent) {
    const rect = svRef.current!.getBoundingClientRect();
    const s = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width));
    const v = Math.max(0, Math.min(1, 1 - (e.clientY - rect.top) / rect.height));
    const next = { ...hsv, s, v };
    setHsv(next);
    commit(next.h, next.s, next.v);
  }

  function hPointer(e: React.PointerEvent) {
    const rect = hRef.current!.getBoundingClientRect();
    const h = Math.max(0, Math.min(360, ((e.clientX - rect.left) / rect.width) * 360));
    const next = { ...hsv, h };
    setHsv(next);
    commit(next.h, next.s, next.v);
  }

  return (
    <div className="flex flex-col gap-3">
      {/* SV box */}
      <div
        ref={svRef}
        className="relative h-36 w-full cursor-crosshair rounded-md"
        style={{ background: `hsl(${hsv.h}, 100%, 50%)` }}
        onPointerDown={(e) => { draggingSV.current = true; e.currentTarget.setPointerCapture(e.pointerId); svPointer(e); }}
        onPointerMove={(e) => { if (draggingSV.current) svPointer(e); }}
        onPointerUp={() => { draggingSV.current = false; }}
      >
        <div className="pointer-events-none absolute inset-0 rounded-md" style={{ background: 'linear-gradient(to right, #fff, transparent)' }} />
        <div className="pointer-events-none absolute inset-0 rounded-md" style={{ background: 'linear-gradient(to top, #000, transparent)' }} />
        <div
          className="pointer-events-none absolute h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white shadow"
          style={{ left: `${hsv.s * 100}%`, top: `${(1 - hsv.v) * 100}%` }}
        />
      </div>

      {/* Hue slider */}
      <div
        ref={hRef}
        className="relative h-4 w-full cursor-pointer rounded-full"
        style={{ background: 'linear-gradient(to right, #f00, #ff0, #0f0, #0ff, #00f, #f0f, #f00)' }}
        onPointerDown={(e) => { draggingH.current = true; e.currentTarget.setPointerCapture(e.pointerId); hPointer(e); }}
        onPointerMove={(e) => { if (draggingH.current) hPointer(e); }}
        onPointerUp={() => { draggingH.current = false; }}
      >
        <div
          className="pointer-events-none absolute top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white shadow"
          style={{ left: `${(hsv.h / 360) * 100}%` }}
        />
      </div>

      {/* Hex input */}
      <input
        value={text}
        onChange={(e) => {
          setText(e.target.value);
          if (/^#[0-9a-f]{6}$/i.test(e.target.value)) {
            const h = hexToHsv(e.target.value);
            setHsv(h);
            onChange(e.target.value);
          }
        }}
        className="rounded-lg border bg-background px-3 py-1.5 font-mono text-sm outline-none focus:ring-2 focus:ring-primary/50"
        placeholder="#rrggbb"
        spellCheck={false}
      />
    </div>
  );
};

// ui/src/lib/components/ColorPicker.svelte
<script lang="ts">
	// Saturation/value square + hue slider + hex field. Ported down from Kibo UI's React component:
	// no alpha (a translucent --primary just breaks the theme), no format dropdown (HEX/RGB/HSL is a
	// dev-facing control), and the hex field is editable here — theirs is read-only, which blocks the
	// one thing people actually want to do, paste a hex.
	//
	// The square is a pointer target with no keyboard equivalent; the hex field is the accessible
	// path to any colour, and the hue slider is a real slider (arrow keys work).
	import { untrack } from 'svelte';
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import { ColorPickerIcon } from '@hugeicons/core-free-icons';
	import { Slider } from '$lib/components/ui/slider';
	import { Input } from '$lib/components/ui/input';
	import { hexToHsv, hsvToHex, type Hsv } from '$lib/color';

	let { value, onchange }: { value: string; onchange: (hex: string) => void } = $props();

	// HSV is the picker's own state, not derived from `value` on every frame: hex can't say where the
	// cursor sat (every hue is black at v=0), so a round-trip per drag would make the square jump.
	let hsv = $state<Hsv>(untrack(() => hexToHsv(value)) ?? { h: 0, s: 1, v: 1 });
	let text = $state(untrack(() => value));

	// Reseat only on changes that came from outside (preset switch, reset). Our own edits already
	// satisfy this equality, so they don't feed back.
	$effect(() => {
		const v = value.toLowerCase();
		if (v === untrack(() => hsvToHex(hsv))) return;
		const next = hexToHsv(v);
		if (next) {
			hsv = next;
			text = v;
		}
	});

	const hasEyeDropper = typeof window !== 'undefined' && 'EyeDropper' in window;

	function set(next: Hsv) {
		hsv = next;
		text = hsvToHex(next);
		onchange(text);
	}

	function pick(e: PointerEvent) {
		const r = (e.currentTarget as HTMLElement).getBoundingClientRect();
		const clamp = (n: number) => Math.min(1, Math.max(0, n));
		set({
			...hsv,
			s: clamp((e.clientX - r.left) / r.width),
			v: 1 - clamp((e.clientY - r.top) / r.height)
		});
	}

	function typed(hex: string) {
		text = hex;
		const next = hexToHsv(hex);
		if (next) {
			hsv = next;
			onchange(hsvToHex(next));
		}
	}

	async function eyeDrop() {
		try {
			// @ts-expect-error — EyeDropper is Chromium-only and untyped; feature-detected above.
			const { sRGBHex } = await new window.EyeDropper().open();
			const next = hexToHsv(sRGBHex);
			if (next) set(next);
		} catch {
			// cancelled with Escape — nothing to do
		}
	}
</script>

<div class="flex w-56 flex-col gap-3">
	<!-- No ARIA role fits a 2D colour field, and "application" is the honest one: keys go to the
	     page, and the hex input below is the accessible route to any colour. -->
	<div
		role="application"
		aria-label="Saturation and brightness"
		class="relative h-32 w-full cursor-crosshair rounded-lg"
		style="background:
			linear-gradient(to top, #000, transparent),
			linear-gradient(to right, #fff, transparent),
			hsl({hsv.h} 100% 50%)"
		onpointerdown={(e) => {
			e.preventDefault();
			e.currentTarget.setPointerCapture(e.pointerId);
			pick(e);
		}}
		onpointermove={(e) => {
			if (e.currentTarget.hasPointerCapture(e.pointerId)) pick(e);
		}}
	>
		<div
			class="pointer-events-none absolute size-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white shadow-[0_0_0_1px_rgba(0,0,0,0.5)]"
			style="left:{hsv.s * 100}%; top:{(1 - hsv.v) * 100}%"
		></div>
	</div>

	<Slider
		type="single"
		aria-label="Hue"
		max={360}
		step={1}
		value={hsv.h}
		onValueChange={(h) => set({ ...hsv, h })}
		class="[&_[data-slot=slider-range]]:bg-transparent [&_[data-slot=slider-track]]:bg-[linear-gradient(to_right,#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00)]"
	/>

	<div class="flex items-center gap-2">
		{#if hasEyeDropper}
			<button
				type="button"
				onclick={eyeDrop}
				aria-label="Pick a colour from the screen"
				class="flex size-8 shrink-0 items-center justify-center rounded-md border text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground"
			>
				<HugeiconsIcon icon={ColorPickerIcon} size={16} />
			</button>
		{/if}
		<Input
			value={text}
			oninput={(e) => typed(e.currentTarget.value)}
			aria-label="Hex colour"
			spellcheck={false}
			class="h-8 bg-secondary px-2 font-mono text-xs shadow-none"
		/>
	</div>
</div>
