// frontend/src/components/ui/ErrorState.tsx
import React from 'react';
import { AlertCircle } from 'lucide-react';
import { cn } from '../../lib/utils';
import { Button } from './Button';

interface ErrorStateProps {
  message?: string;
  onRetry?: () => void;
  className?: string;
}

export const ErrorState: React.FC<ErrorStateProps> = ({ message, onRetry, className }) => (
  <div className={cn('flex flex-col items-center gap-3 py-12 text-center', className)}>
    <AlertCircle className="h-8 w-8 text-destructive/60" />
    <p className="text-sm text-muted-foreground">{message ?? 'Something went wrong.'}</p>
    {onRetry && <Button size="sm" variant="outline" onClick={onRetry}>Try again</Button>}
  </div>
);

// ui/src/lib/components/ErrorState.svelte
<script lang="ts">
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import { RefreshIcon } from '@hugeicons/core-free-icons';
	import { Button } from '$lib/components/ui/button';

	let { message, onRetry }: { message: string; onRetry: () => void } = $props();
</script>

<div class="flex flex-col items-start gap-3">
	<p class="text-sm text-destructive">{message}</p>
	<!-- shadcn's Button spreads onclick straight onto the real <button>, so passing `onRetry` directly
	     would hand the callback a MouseEvent — any retry handler with an optional parameter (like
	     home's `load`) would silently receive it as an argument instead of its default. -->
	<Button variant="outline" size="sm" class="gap-2" onclick={() => onRetry()}>
		<HugeiconsIcon icon={RefreshIcon} class="h-4 w-4" /> Try again
	</Button>
</div>
