// frontend/src/components/LyricsView.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import * as api from '../lib/api';
import { usePlayer } from '../features/player/PlayerContext';
import { cn } from '../lib/utils';

function durationSecs(d?: string): number | undefined {
  if (!d) return undefined;
  const parts = d.split(':').map(Number);
  if (!parts.length || parts.some(Number.isNaN)) return undefined;
  return parts.reduce((a, b) => a * 60 + b, 0);
}

interface Props { expanded?: boolean }

export const LyricsView: React.FC<Props> = ({ expanded = false }) => {
  const { now, queue, position, paused, seek } = usePlayer();
  const [lyrics, setLyrics] = useState<api.Lyrics | null>(null);
  const [loading, setLoading] = useState(false);
  const scrollerRef = useRef<HTMLDivElement>(null);
  const requested = useRef('');
  const userScrollUntil = useRef(0);
  const hasScrolled = useRef(false);
  const [interpolatedPos, setInterpolatedPos] = useState(position);

  // Interpolated position clock
  useEffect(() => {
    if (paused) { setInterpolatedPos(position); return; }
    const base = position;
    const baseAt = performance.now();
    setInterpolatedPos(position);
    let id = requestAnimationFrame(function tick() {
      setInterpolatedPos(base + (performance.now() - baseAt) / 1000);
      id = requestAnimationFrame(tick);
    });
    return () => cancelAnimationFrame(id);
  }, [position, paused]);

  const posMs = interpolatedPos * 1000;

  // Fetch lyrics when track changes
  useEffect(() => {
    if (!now) { requested.current = ''; setLyrics(null); setLoading(false); return; }
    if (now.videoId === requested.current) return;
    const id = (requested.current = now.videoId);
    setLoading(true); setLyrics(null);
    const album = queue.items[queue.currentIndex]?.album;
    api.getLyrics({
      videoId: id, title: now.title, artists: now.artists,
      album: album ?? undefined, duration: durationSecs(now.duration),
    }).then((l) => {
      if (requested.current !== id) return;
      setLyrics(l); setLoading(false); hasScrolled.current = false;
    }).catch(() => {
      if (requested.current === id) setLoading(false);
    });
  }, [now?.videoId]);

  // Active line index
  const activeIndex = (() => {
    if (!lyrics?.synced) return -1;
    let i = -1;
    for (let j = 0; j < lyrics.lines.length; j++) {
      const t = lyrics.lines[j].time_ms;
      if (t === undefined) continue;
      if (t > posMs) break;
      i = j;
    }
    return i;
  })();

  // Auto-scroll
  useEffect(() => {
    if (activeIndex < 0 || !scrollerRef.current || Date.now() < userScrollUntil.current) return;
    scrollerRef.current.querySelector(`[data-line="${activeIndex}"]`)?.scrollIntoView({
      behavior: hasScrolled.current ? 'smooth' : 'instant',
      block: 'center',
    });
    hasScrolled.current = true;
  }, [activeIndex]);

  function onUserScroll() { userScrollUntil.current = Date.now() + 3000; }

  function seekTo(line: api.LyricLine) {
    if (line.time_ms === undefined) return;
    const secs = line.time_ms / 1000;
    userScrollUntil.current = 0;
    seek(secs);
  }

  function getWordProgress(word: api.LyricWord, currentMs: number): number {
    if (currentMs <= word.start_ms) return 0;
    if (currentMs >= word.end_ms) return 1;
    const dur = word.end_ms - word.start_ms;
    return dur <= 0 ? 1 : (currentMs - word.start_ms) / dur;
  }

  return (
    <>
      <div
        ref={scrollerRef}
        onWheel={onUserScroll}
        onTouchMove={onUserScroll}
        onPointerDown={onUserScroll}
        className={cn('min-h-0 flex-1 overflow-y-auto py-6', expanded ? 'px-10' : 'px-5')}
      >
        {loading ? (
          <div className="space-y-3">
            {Array.from({ length: 8 }).map((_, i) => (
              <div key={i} className="h-5 animate-pulse rounded bg-muted" style={{ width: `${55 + (i * 17) % 40}%` }} />
            ))}
          </div>
        ) : lyrics?.instrumental ? (
          <p className="py-8 text-center text-lg text-muted-foreground">Instrumental ♪</p>
        ) : lyrics?.synced ? (
          <div className={cn('py-[35vh]', expanded && 'mx-auto max-w-3xl')}>
            {lyrics.lines.map((line, i) => {
              const isActive = i === activeIndex;
              const isPast = i < activeIndex;
              return (
                <button
                  key={i}
                  data-line={i}
                  onClick={() => seekTo(line)}
                  className={cn(
                    'block w-full origin-left cursor-pointer text-left font-heading font-bold leading-snug transition-[color,transform] duration-300 ease-out hover:text-foreground',
                    expanded ? 'py-3 text-3xl' : 'py-2 text-xl',
                    isActive ? 'scale-[1.04] text-foreground' : isPast ? 'text-muted-foreground/40' : 'text-muted-foreground/70',
                  )}
                >
                  {line.words && line.words.length > 0 ? (
                    <span className="inline-flex flex-wrap items-baseline">
                      {line.words.map((word, wIdx) => {
                        const isWordEnd = word.text.endsWith(' ');
                        const cleanText = word.text.trimEnd();
                        if (isActive) {
                          const progress = getWordProgress(word, posMs);
                          const pct = Math.round(Math.min(1, Math.max(0, progress)) * 100);
                          return (
                            <span
                              key={wIdx}
                              className={cn('inline-block bg-clip-text text-transparent [-webkit-text-fill-color:transparent] transition-transform duration-100 ease-out', isWordEnd && 'mr-[0.26em]', progress > 0 && progress < 1 && 'scale-[1.03]')}
                              style={{ backgroundImage: `linear-gradient(90deg, var(--foreground) ${pct}%, var(--muted-foreground) ${pct}%)` }}
                            >{cleanText}</span>
                          );
                        }
                        return (
                          <span key={wIdx} className={cn('inline-block', isWordEnd && 'mr-[0.26em]', isPast ? 'text-muted-foreground/40' : 'text-muted-foreground/70')}>
                            {cleanText}
                          </span>
                        );
                      })}
                    </span>
                  ) : (
                    <span>{line.text || '♪'}</span>
                  )}
                  {line.translation && (
                    <p className="mt-1 text-sm font-normal italic tracking-wide opacity-80">{line.translation}</p>
                  )}
                </button>
              );
            })}
          </div>
        ) : lyrics ? (
          <div className={cn('space-y-2 leading-relaxed text-foreground/90', expanded ? 'mx-auto max-w-3xl text-xl' : 'text-[15px]')}>
            {lyrics.lines.map((line, i) => (
              line.text ? (
                <div key={i}>
                  <p>{line.text}</p>
                  {line.translation && <p className="text-xs italic text-muted-foreground">{line.translation}</p>}
                </div>
              ) : <div key={i} className="h-4" />
            ))}
          </div>
        ) : (
          <p className="py-8 text-center text-sm text-muted-foreground">No lyrics found for this track.</p>
        )}
      </div>
      {lyrics && !loading && (
        <p className="border-t px-4 py-2 text-xs text-muted-foreground">
          {lyrics.source.startsWith('Source:') ? lyrics.source : `Lyrics from ${lyrics.source}`}
        </p>
      )}
    </>
  );
};

// ui/src/lib/components/LyricsView.svelte
<script lang="ts">
	import * as api from '$lib/api';
	import { playback } from '$lib/player.svelte';

	// `expanded` only sizes the type and centres the column. The owner of the extra room (the side
	// panel, or the now-playing view) decides how much there is. Toggling it must not remount this
	// component, or the lyrics refetch and the scroll position is lost.
	let { expanded = false }: { expanded?: boolean } = $props();

	/** "3:21" / "1:02:03" → seconds. */
	function durationSecs(d?: string): number | undefined {
		if (!d) return undefined;
		const parts = d.split(':').map(Number);
		if (!parts.length || parts.some(Number.isNaN)) return undefined;
		return parts.reduce((a, b) => a * 60 + b, 0);
	}

	let lyrics = $state<api.Lyrics | null>(null);
	let loading = $state(true);
	let scroller: HTMLElement | undefined = $state();

	// videoId of the fetch whose result is (or will be) shown — guards stale responses.
	let requested = '';

	$effect(() => {
		const now = playback.now;
		if (!now) {
			requested = '';
			lyrics = null;
			loading = false;
			return;
		}
		if (now.videoId === requested) return;
		const id = (requested = now.videoId);
		loading = true;
		lyrics = null;
		// Album isn't in now-playing, but the queue item usually has it — better LRCLIB matching.
		const album = playback.queue.items[playback.queue.currentIndex]?.album;
		api.getLyrics({
			videoId: id,
			title: now.title,
			artists: now.artists,
			album: album ?? undefined,
			// The track's own length — NOT playback.duration, which still holds the previous
			// track's value for a moment after a track change.
			duration: durationSecs(now.duration)
		})
			.then((l) => {
				if (requested !== id) return;
				lyrics = l;
				loading = false;
				hasScrolled = false; // first positioning on a new track is an instant jump
			})
			.catch(() => {
				if (requested !== id) return;
				loading = false;
			});
	});

	// Last synced line whose cue has passed (lines arrive sorted by time).
	const activeIndex = $derived.by(() => {
		if (!lyrics?.synced) return -1;
		const currentMs = posMs;
		let i = -1;
		for (let j = 0; j < lyrics.lines.length; j++) {
			const t = lyrics.lines[j].time_ms;
			if (t === undefined) continue;
			if (t > currentMs) break;
			i = j;
		}
		return i;
	});

	// Auto-scroll pauses while the user is scrolling (wheel/touch/scrollbar), resumes after 3s.
	// Tracked via input events, not `scroll`, so our own smooth scrolls don't trip it.
	let userScrollUntil = 0;
	let hasScrolled = false;
	function onUserScroll() {
		userScrollUntil = Date.now() + 3000;
	}

	let wasExpanded: boolean | undefined;

	$effect(() => {
		const i = activeIndex;
		// Re-centre after the layout width/font changes, and jump rather than glide across it.
		// (Also fires on the first run, where both values are already at their defaults.)
		if (expanded !== wasExpanded) {
			wasExpanded = expanded;
			hasScrolled = false;
			userScrollUntil = 0;
		}
		if (i < 0 || !scroller || Date.now() < userScrollUntil) return;
		scroller.querySelector(`[data-line="${i}"]`)?.scrollIntoView({
			// Opening mid-song jumps straight to the line; after that, glide.
			behavior: hasScrolled ? 'smooth' : 'instant',
			block: 'center'
		});
		hasScrolled = true;
	});

	function seekTo(line: api.LyricLine) {
		if (line.time_ms === undefined) return;
		const secs = line.time_ms / 1000;
		playback.position = secs; // optimistic — the mpv tick confirms
		userScrollUntil = 0; // jump the view along with the seek
		api.seek(secs);
	}

	// mpv's position arrives ~4x a second. Run a local clock forward from each one so the karaoke
	// sweep moves every frame instead of stepping four times a second.
	let interpolatedPosSecs = $state(playback.position);

	$effect(() => {
		const pos = playback.position;
		if (playback.paused) {
			interpolatedPosSecs = pos;
			return;
		}
		// Rebase on every run. Rebasing only when the value moved kept the base timestamp from
		// before a pause, so resuming after N seconds paused ran the clock N seconds fast until
		// the next tick corrected it.
		const base = pos;
		const baseAt = performance.now();
		interpolatedPosSecs = pos;
		let frameId = requestAnimationFrame(function tick() {
			interpolatedPosSecs = base + (performance.now() - baseAt) / 1000;
			frameId = requestAnimationFrame(tick);
		});
		return () => cancelAnimationFrame(frameId);
	});

	const posMs = $derived(interpolatedPosSecs * 1000);

	function getWordProgress(word: api.LyricWord, currentMs: number): number {
		if (currentMs <= word.start_ms) return 0;
		if (currentMs >= word.end_ms) return 1;
		const dur = word.end_ms - word.start_ms;
		if (dur <= 0) return 1;
		return (currentMs - word.start_ms) / dur;
	}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -- handlers only detect scroll intent -->
<div
	bind:this={scroller}
	onwheel={onUserScroll}
	ontouchmove={onUserScroll}
	onpointerdown={onUserScroll}
	class="min-h-0 flex-1 overflow-y-auto py-6 {expanded ? 'px-10' : 'px-5'}"
>
	{#if loading}
		<div class="space-y-3">
			{#each { length: 8 } as _, i (i)}
				<div class="h-5 animate-pulse rounded bg-muted" style="width:{55 + ((i * 17) % 40)}%"></div>
			{/each}
		</div>
	{:else if lyrics?.instrumental}
		<p class="py-8 text-center text-lg text-muted-foreground">Instrumental ♪</p>
	{:else if lyrics && lyrics.synced}
		<!-- Padding lets the first/last lines center-scroll. -->
		<div class="py-[35vh] {expanded ? 'mx-auto max-w-3xl' : ''}">
			{#each lyrics.lines as line, i (i)}
				{@const isActive = i === activeIndex}
				{@const isPast = i < activeIndex}
				<button
					data-line={i}
					onclick={() => seekTo(line)}
					class="block w-full origin-left cursor-pointer text-left font-heading font-bold leading-snug transition-[color,transform] duration-300 ease-out hover:text-foreground
						{expanded ? 'py-3 text-3xl' : 'py-2 text-xl'}
						{isActive
						? 'scale-[1.04] text-foreground'
						: isPast
							? 'text-muted-foreground/40'
							: 'text-muted-foreground/70'}"
				>
					{#if line.words && line.words.length > 0}
						<!-- Word-by-Word Karaoke Sweep Animation (Better-Lyrics style, highly optimized) -->
						<span class="inline-flex flex-wrap items-baseline">
							{#each line.words as word, wIdx (wIdx)}
								{@const isWordEnd = word.text.endsWith(' ')}
								{@const cleanText = word.text.trimEnd()}
								{#if isActive}
									{@const progress = getWordProgress(word, posMs)}
									{@const pct = Math.round(Math.min(1, Math.max(0, progress)) * 100)}
									{@const isCurrentWord = progress > 0 && progress < 1}
									<!-- Only the gradient stop moves per frame; the clip/fill are static, so they
									     live in the class and aren't re-serialised 60 times a second. Both
									     colours are theme tokens: the sung half was hardcoded white, which is
									     invisible on every light theme. -->
									<span
										class="inline-block bg-clip-text text-transparent [-webkit-text-fill-color:transparent] transition-transform duration-100 ease-out {isWordEnd ? 'mr-[0.26em]' : ''} {isCurrentWord
											? 'scale-[1.03]'
											: ''}"
										style="background-image: linear-gradient(90deg, var(--foreground) {pct}%, var(--muted-foreground) {pct}%)"
									>
										{cleanText}
									</span>
								{:else}
									<span class="inline-block {isWordEnd ? 'mr-[0.26em]' : ''} {isPast ? 'text-muted-foreground/40' : 'text-muted-foreground/70'}">
										{cleanText}
									</span>
								{/if}
							{/each}
						</span>
					{:else}
						<span>{line.text || '♪'}</span>
					{/if}

					<!-- Translation line rendering -->
					{#if line.translation}
						<p class="mt-1 text-sm font-normal italic tracking-wide opacity-80 transition-opacity">
							{line.translation}
						</p>
					{/if}
				</button>
			{/each}
		</div>
	{:else if lyrics}
		<div
			class="space-y-2 leading-relaxed text-foreground/90 {expanded
				? 'mx-auto max-w-3xl text-xl'
				: 'text-[15px]'}"
		>
			{#each lyrics.lines as line, i (i)}
				{#if line.text}
					<div>
						<p>{line.text}</p>
						{#if line.translation}
							<p class="text-xs italic text-muted-foreground">{line.translation}</p>
						{/if}
					</div>
				{:else}
					<div class="h-4"></div>
				{/if}
			{/each}
		</div>
	{:else}
		<p class="py-8 text-center text-sm text-muted-foreground">No lyrics found for this track.</p>
	{/if}
</div>
{#if lyrics && !loading}
	<p class="border-t px-4 py-2 text-xs text-muted-foreground">
		{lyrics.source.startsWith('Source:') ? lyrics.source : `Lyrics from ${lyrics.source}`}
	</p>
{/if}
