// frontend/src/features/player/components/PlayerBar.tsx
import React, { useState, useCallback, useRef } from 'react';
import {
  Play, Pause, SkipForward, SkipBack, Shuffle, Repeat, Repeat1,
  Mic2, ListMusic, Volume2, VolumeX, ChevronUp, ChevronDown, Heart, Plus,
} from 'lucide-react';
import { usePlayer } from '../PlayerContext';
import { thumb } from '../../../lib/thumb';
import { isLocalId } from '../../../lib/api';
import { cn } from '../../../lib/utils';
import { Marquee } from '../../../components/Marquee';
import { ArtistLine } from '../../../components/ArtistLine';
import { Slider } from '../../../components/ui/Slider';
import { useIsMobile } from '../../../lib/mobile';

const fmt = (secs: number | string | undefined | null) => {
  const n = Number(secs);
  if (!Number.isFinite(n) || n < 0) return '0:00';
  const t = Math.floor(n);
  const h = Math.floor(t / 3600);
  const m = Math.floor((t % 3600) / 60);
  const s = t % 60;
  const mm = h ? m.toString().padStart(2, '0') : `${m}`;
  return `${h ? `${h}:` : ''}${mm}:${s.toString().padStart(2, '0')}`;
};

interface PlayerBarProps {
  className?: string;
  queueOpen?: boolean;
  onToggleQueue?: () => void;
  lyricsOpen?: boolean;
  onToggleLyrics?: () => void;
}

export const PlayerBar: React.FC<PlayerBarProps> = ({
  className,
  queueOpen = false,
  onToggleQueue,
  lyricsOpen = false,
  onToggleLyrics,
}) => {
  const {
    now, queue, paused, position, duration, volume, np,
    togglePause, nextTrack, prevTrack, toggleShuffle, cycleRepeat,
    seek, dragVolume, commitVolume, toggleNowPlayingLike,
    setNpOpen, openAddToPlaylist,
  } = usePlayer();

  const rating = now?.rating ?? 'indifferent';
  const shuffleOn = queue.shuffle ?? false;
  const repeat = queue.repeat ?? 'off';
  const mobile = useIsMobile();
  const [justLiked, setJustLiked] = useState(false);

  const toggleLike = useCallback(() => {
    if (rating !== 'like') setJustLiked(true);
    toggleNowPlayingLike();
  }, [rating, toggleNowPlayingLike]);

  const [seekDrag, setSeekDrag] = useState<number | null>(null);
  const shownPosition = seekDrag ?? position;
  const progressPct = duration > 0 ? (shownPosition / duration) * 100 : 0;

  const pressedControl = useRef(false);
  const isControl = (t: EventTarget | null) =>
    !!(t && (t as HTMLElement).closest?.('button,a,input,[role="button"]'));

  const onBarClick = useCallback(() => {
    if (pressedControl.current) return;
    setNpOpen(!np.open);
  }, [np.open, setNpOpen]);

  if (!now) return null;

  // Mobile mini-player: a single clean row (thumb + title/artist + prev/play/next), YT-Music style.
  // Everything else — shuffle, repeat, seek, lyrics, queue, like, add, volume — lives in the full
  // NowPlaying view so the strip never runs out of room on a phone screen. Tap the bar to expand.
  if (mobile) {
    return (
      <footer
        className={cn(
          'relative flex h-16 shrink-0 items-center gap-3 border-t bg-card px-3',
          className,
        )}
        onPointerDown={(e) => { pressedControl.current = isControl(e.target); }}
        onClick={(e) => { if (!isControl(e.target)) onBarClick(); }}
      >
        {now.thumbnail ? (
          <img src={thumb(now.thumbnail, 120)} alt="" className="size-12 shrink-0 rounded-lg object-cover" />
        ) : (
          <div className="flex size-12 shrink-0 items-center justify-center rounded-lg bg-muted text-muted-foreground/50">
            <Play className="h-5 w-5" />
          </div>
        )}
        <div className="min-w-0 flex-1">
          <Marquee text={now.title ?? 'Nothing playing'} className="text-sm font-medium" />
          <ArtistLine
            runs={now.artistRuns}
            text={now.artists ?? ''}
            className="block truncate text-xs text-muted-foreground"
          />
        </div>
        <button
          className="flex size-9 shrink-0 items-center justify-center rounded-md text-muted-foreground transition-colors hover:text-foreground"
          onClick={(e) => { e.stopPropagation(); prevTrack(); }}
          aria-label="Previous"
        >
          <SkipBack className="size-5" />
        </button>
        <button
          className="flex size-11 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-sm active:scale-95"
          onClick={(e) => { e.stopPropagation(); togglePause(); }}
          aria-label={paused ? 'Play' : 'Pause'}
        >
          {paused ? <Play className="size-5" /> : <Pause className="size-5" />}
        </button>
        <button
          className="flex size-9 shrink-0 items-center justify-center rounded-md text-muted-foreground transition-colors hover:text-foreground"
          onClick={(e) => { e.stopPropagation(); nextTrack(); }}
          aria-label="Next"
        >
          <SkipForward className="size-5" />
        </button>
      </footer>
    );
  }

  return (
    <footer
      className={cn(
        'relative flex items-center gap-2 border-t bg-card px-2 py-2.5 animate-in slide-in-from-bottom-8 duration-200 sm:gap-4 sm:px-4 sm:py-3',
        className,
      )}
      onPointerDown={(e) => { pressedControl.current = isControl(e.target); }}
      onClick={(e) => { if (!isControl(e.target)) onBarClick(); }}
    >
      {/* Left: now-playing info */}
      <div className="flex min-w-0 flex-1 items-center gap-3">
        {now.thumbnail ? (
          <img
            src={thumb(now.thumbnail, 120)}
            alt=""
            style={{ maxWidth: 'none' }}
            className="h-12 w-12 shrink-0 rounded-lg object-cover"
          />
        ) : (
          <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-muted text-muted-foreground/50">
            <Play className="h-5 w-5" />
          </div>
        )}
        <div className="min-w-0">
          <div className="flex items-center gap-1.5">
            <Marquee text={now.title ?? 'Nothing playing'} className="text-sm font-medium" />
          </div>
          <ArtistLine
            runs={now.artistRuns}
            text={now.artists ?? ''}
            className="block max-w-full truncate text-xs text-muted-foreground"
          />
        </div>
        {now && (
          <div className="flex items-center">
            {!isLocalId(now.videoId) && (
              <button
                className="hidden h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition hover:bg-muted hover:text-foreground lg:inline-flex"
                onClick={(e) => { e.stopPropagation(); toggleLike(); }}
                aria-label="Like"
              >
                <span
                  className={cn('inline-flex', justLiked && 'animate-heart-pop')}
                  onAnimationEnd={() => setJustLiked(false)}
                >
                  <Heart className={cn('h-4 w-4', rating === 'like' ? 'fill-current text-primary' : '')} />
                </span>
              </button>
            )}
            {!isLocalId(now.videoId) && (
              <button
                className="hidden h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition hover:bg-muted hover:text-foreground lg:inline-flex"
                onClick={(e) => {
                  e.stopPropagation();
                  openAddToPlaylist([{
                    video_id: now.videoId,
                    title: now.title,
                    artists: now.artists,
                    artist_id: now.artistId,
                    thumbnail: now.thumbnail,
                    duration: now.duration,
                  }]);
                }}
                aria-label="Add to playlist"
              >
                <Plus className="h-4 w-4" />
              </button>
            )}
          </div>
        )}
      </div>

      {/* Center: transport */}
      <div className="flex flex-[1.5] flex-col items-center gap-1">
        <div className="flex items-center gap-1">
          <button
            className={cn(
              'flex h-8 w-8 items-center justify-center rounded-md transition-colors',
              shuffleOn ? 'text-primary' : 'text-muted-foreground hover:text-foreground',
            )}
            onClick={(e) => { e.stopPropagation(); toggleShuffle(); }}
            aria-label="Shuffle"
            aria-pressed={shuffleOn}
          >
            <Shuffle className="h-4 w-4" />
          </button>
          <button
            className="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:text-foreground"
            onClick={(e) => { e.stopPropagation(); prevTrack(); }}
            aria-label="Previous"
          >
            <SkipBack className="h-5 w-5" />
          </button>
          <button
            className="flex h-10 w-10 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-sm transition-transform hover:scale-105 active:scale-95"
            onClick={(e) => { e.stopPropagation(); togglePause(); }}
            aria-label={paused ? 'Play' : 'Pause'}
          >
            {paused ? <Play className="h-5 w-5" /> : <Pause className="h-5 w-5" />}
          </button>
          <button
            className="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:text-foreground"
            onClick={(e) => { e.stopPropagation(); nextTrack(); }}
            aria-label="Next"
          >
            <SkipForward className="h-5 w-5" />
          </button>
          <button
            className={cn(
              'flex h-8 w-8 items-center justify-center rounded-md transition-colors',
              repeat !== 'off' ? 'text-primary' : 'text-muted-foreground hover:text-foreground',
            )}
            onClick={(e) => { e.stopPropagation(); cycleRepeat(); }}
            aria-label={`Repeat: ${repeat}`}
            aria-pressed={repeat !== 'off'}
          >
            {repeat === 'one' ? <Repeat1 className="h-4 w-4" /> : <Repeat className="h-4 w-4" />}
          </button>
        </div>
        <div className="flex w-full max-w-md items-center gap-2 text-xs text-muted-foreground">
          <span className="tabular-nums">{fmt(shownPosition)}</span>
          <Slider
            className="flex-1"
            min={0}
            max={duration || 0}
            step={0.1}
            value={[shownPosition]}
            onValueChange={(v) => setSeekDrag(v[0])}
            onValueCommit={(v) => { seek(v[0]); setSeekDrag(null); }}
          />
          <span className="tabular-nums">{fmt(duration)}</span>
        </div>
      </div>

      {/* Right: volume + toggles */}
      <div className="flex flex-1 items-center justify-end gap-2">
        <div className="hidden items-center gap-1 md:flex">
          <button
            className="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:text-foreground"
            onClick={(e) => { e.stopPropagation(); commitVolume(volume === 0 ? 50 : 0); }}
            aria-label={volume === 0 ? 'Unmute' : 'Mute'}
          >
            {volume === 0 ? <VolumeX className="h-4 w-4" /> : <Volume2 className="h-4 w-4" />}
          </button>
          <Slider
            className="w-24"
            min={0}
            max={100}
            step={1}
            value={[volume]}
            onValueChange={(v) => dragVolume(v[0])}
            onValueCommit={(v) => commitVolume(v[0])}
          />
        </div>
        <div className="flex items-center gap-0.5">
          <button
            className={cn(
              'flex h-8 w-8 items-center justify-center rounded-md transition-colors',
              lyricsOpen ? 'bg-secondary text-foreground' : 'text-muted-foreground hover:text-foreground',
            )}
            onClick={(e) => { e.stopPropagation(); onToggleLyrics?.(); }}
            aria-label="Toggle lyrics"
          >
            <Mic2 className="h-5 w-5" />
          </button>
          <button
            className={cn(
              'flex h-8 w-8 items-center justify-center rounded-md transition-colors',
              queueOpen ? 'bg-secondary text-foreground' : 'text-muted-foreground hover:text-foreground',
            )}
            onClick={(e) => { e.stopPropagation(); onToggleQueue?.(); }}
            aria-label="Toggle queue"
          >
            <ListMusic className="h-5 w-5" />
          </button>
          <button
            className="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:text-foreground"
            onClick={(e) => { e.stopPropagation(); setNpOpen(!np.open); }}
            aria-label={np.open ? 'Minimise player' : 'Open player'}
            aria-expanded={np.open}
          >
            {np.open ? <ChevronDown className="h-5 w-5" /> : <ChevronUp className="h-5 w-5" />}
          </button>
        </div>
      </div>
    </footer>
  );
};

// ui/src/lib/components/PlayerBar.svelte
<script lang="ts">
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import {
		PreviousIcon,
		NextIcon,
		PlayIcon,
		PauseIcon,
		ShuffleIcon,
		RepeatIcon,
		RepeatOne01Icon,
		Queue01Icon,
		Mic01Icon,
		VolumeHighIcon,
		VolumeMute02Icon,
		FavouriteIcon,
		Add01Icon,
		InfinityIcon,
		MinimizeScreenIcon,
		MusicNote01Icon,
		ArrowUp01Icon,
		ArrowDown01Icon
	} from '@hugeicons/core-free-icons';
	import { fade } from 'svelte/transition';
	import { Button } from '$lib/components/ui/button';
	import * as api from '$lib/api';
	import {
		np,
		playback,
		commitVolume,
		cycleRepeat,
		dragVolume,
		openAddToPlaylist,
		openMiniPlayer,
		toggleMute,
		toggleNowPlayingLike
	} from '$lib/player.svelte';
	import { thumb } from '$lib/thumb';
	import ArtistLine from './ArtistLine.svelte';
	import Marquee from './Marquee.svelte';
	import TrackMenu from './TrackMenu.svelte';
	import { isMobile } from '$lib/mobile.svelte';

	let {
		onToggleQueue,
		queueOpen,
		onToggleLyrics,
		lyricsOpen
	}: {
		onToggleQueue: () => void;
		queueOpen: boolean;
		onToggleLyrics: () => void;
		lyricsOpen: boolean;
	} = $props();

	// Pop the heart once when the user favourites (not when un-favouriting). Reset on animation end
	// so the next like can replay it.
	let justLiked = $state(false);

	function toggleLike() {
		if (playback.rating !== 'like') justLiked = true;
		toggleNowPlayingLike();
	}

	const fmt = (secs: number) => {
		if (!secs || secs < 0) return '0:00';
		const t = Math.floor(secs);
		const h = Math.floor(t / 3600);
		const m = Math.floor((t % 3600) / 60);
		const s = t % 60;
		const mm = h ? m.toString().padStart(2, '0') : `${m}`;
		return `${h ? `${h}:` : ''}${mm}:${s.toString().padStart(2, '0')}`;
	};

	const shuffleOn = $derived(playback.queue.shuffle ?? false);
	const repeat = $derived(playback.queue.repeat ?? 'off');

	// The current track was appended by autoplay → show the subtle ∞ badge next to the title.
	// Matched against the now-playing videoId so a transient queue/now-playing mismatch (mid
	// gapless advance) can't flash the badge on the wrong song.
	const autoplayTrack = $derived.by(() => {
		const cur = playback.queue.items[playback.queue.currentIndex];
		return !!cur?.autoplay && cur.video_id === playback.now?.videoId;
	});

	// The ⋮ menu needs the full SongItem — NowPlaying carries no album_id. Take it from the queue
	// row, matched on videoId so a mid-advance mismatch can't point the menu at the wrong song.
	const currentSong = $derived.by(() => {
		const cur = playback.queue.items[playback.queue.currentIndex];
		return cur?.video_id === playback.now?.videoId ? cur : null;
	});

	// Seek: while dragging, hold a local value so incoming mpv position ticks can't yank the thumb
	// back under the pointer; only invoke the (expensive) seek on release.
	let seekDrag = $state<number | null>(null);
	const shownPosition = $derived(seekDrag ?? playback.position);

	function onSeekInput(e: Event) {
		seekDrag = Number((e.target as HTMLInputElement).value);
	}
	function onSeekCommit(e: Event) {
		const v = Number((e.target as HTMLInputElement).value);
		playback.position = v;
		seekDrag = null;
		api.seek(v);
	}

	const onVolume = (e: Event) => dragVolume(Number((e.target as HTMLInputElement).value));
	const onVolumeCommit = (e: Event) => commitVolume(Number((e.target as HTMLInputElement).value));

	const isControl = (t: EventTarget | null) =>
		!!(t as HTMLElement | null)?.closest?.('button, a, input, [role="button"]');

	// Dragging a slider past its end and releasing outside it retargets the click at the bar (the
	// click lands on the common ancestor of press and release), which used to toggle the view.
	// So judge by where the press started, not where the release happened.
	let pressedControl = false;

	// Anywhere on the bar that isn't a control opens (or closes) the now-playing view: the bar is
	// what's left of it once it's minimised, so it's the way back in. Deliberately no pointer
	// cursor, because this is the whole bar, not a button, and every real button keeps its own click.
	function onBarClick(e: MouseEvent) {
		if (pressedControl || isControl(e.target)) return;
		np.open = !np.open;
	}
</script>

<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions, a11y_no_noninteractive_element_interactions -->
{#if isMobile}
	<!-- Phone mini-player, Spotify-style: a slim strip above the tab bar — art, title, play/pause,
	     next. A hairline progress bar runs along its top edge (the seek slider lives in the
	     full-screen view). Tapping anywhere that isn't a control opens that view (shared handler). -->
	<footer
		onpointerdown={(e) => (pressedControl = isControl(e.target))}
		onclick={onBarClick}
		class="relative flex items-center gap-3 border-t bg-card py-2 pl-3 pr-2"
	>
		<div
			class="absolute left-0 top-0 h-0.5 bg-primary transition-[width] duration-300 ease-linear"
			style="width:{playback.duration ? (playback.position / playback.duration) * 100 : 0}%"
		></div>
		{#key playback.now?.videoId}
			{#if playback.now?.thumbnail}
				<img
					src={thumb(playback.now.thumbnail, 120)}
					alt=""
					style="max-width:none"
					class="h-10 w-10 shrink-0 rounded-md object-cover"
					in:fade={{ duration: 250 }}
				/>
			{:else}
				<div
					class="flex h-10 w-10 shrink-0 items-center justify-center rounded-md bg-muted text-muted-foreground/50"
				>
					<HugeiconsIcon icon={MusicNote01Icon} class="h-4 w-4" />
				</div>
			{/if}
		{/key}
		<div class="min-w-0 flex-1">
			<Marquee text={playback.now?.title ?? 'Nothing playing'} class="text-sm font-medium" />
			<ArtistLine
				runs={playback.now?.artistRuns}
				text={playback.now?.artists ?? ''}
				class="block truncate text-xs text-muted-foreground"
			/>
		</div>
		<Button variant="ghost" size="icon" class="size-11" onclick={() => api.togglePause()} aria-label="Play/pause">
			<!-- altIcon/showAlt, not a ternary: `icon` freezes at mount. -->
			<HugeiconsIcon icon={PauseIcon} altIcon={PlayIcon} showAlt={playback.paused} class="h-6 w-6" />
		</Button>
		<Button variant="ghost" size="icon" class="size-11" onclick={() => api.nextTrack()} aria-label="Next">
			<HugeiconsIcon icon={NextIcon} class="h-6 w-6" />
		</Button>
	</footer>
{:else}
<!-- The chevron button below is the keyboard equivalent of clicking the bar, so the bar itself
     stays a plain region rather than becoming a focusable control wrapping every other control. -->
<footer
	onpointerdown={(e) => (pressedControl = isControl(e.target))}
	onclick={onBarClick}
	class="flex items-center gap-2 border-t bg-card px-2 py-2.5 sm:gap-4 sm:px-4 sm:py-3"
>
	<!-- Now playing -->
	<div class="flex min-w-0 flex-1 items-center gap-3">
		{#key playback.now?.videoId}
			{#if playback.now?.thumbnail}
				<img
					src={thumb(playback.now.thumbnail, 120)}
					alt=""
					style="max-width:none"
					class="h-12 w-12 shrink-0 rounded-lg object-cover"
					in:fade={{ duration: 250 }}
				/>
			{:else}
				<div
					class="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-muted text-muted-foreground/50"
				>
					<HugeiconsIcon icon={MusicNote01Icon} class="h-5 w-5" />
				</div>
			{/if}
		{/key}
		<div class="min-w-0">
			<div class="flex items-center gap-1.5">
				<Marquee
					text={playback.now?.title ?? 'Nothing playing'}
					class="text-sm font-medium"
				/>
				{#if autoplayTrack}
					<span
						class="shrink-0 text-muted-foreground"
						title="Playing similar music (Autoplay)"
						in:fade={{ duration: 200 }}
					>
						<HugeiconsIcon icon={InfinityIcon} class="h-3.5 w-3.5" />
					</span>
				{/if}
			</div>
			<ArtistLine
				runs={playback.now?.artistRuns}
				text={playback.now?.artists ?? ''}
				marquee
				class="block max-w-full text-xs text-muted-foreground"
			/>
		</div>
		{#if playback.now}
			<div class="flex items-center">
				<!-- A local file has no YouTube identity (see api.isLocalId): nothing to like, and no
				     YTM playlist to add it to. Below lg both drop and the ⋮ menu carries them instead:
				     on a narrow window three buttons here leave the title almost no room. lg, not md:
				     the window's minWidth is 900 (tauri.conf.json), so md never fires. -->
				{#if !api.isLocalId(playback.now.videoId)}
					<Button
						variant="ghost"
						size="icon-sm"
						class="hidden lg:inline-flex"
						onclick={toggleLike}
						aria-label="Like"
					>
						<span
							class="inline-flex"
							class:animate-heart-pop={justLiked}
							onanimationend={() => (justLiked = false)}
						>
							<HugeiconsIcon
								icon={FavouriteIcon}
								class="h-4 w-4 {playback.rating === 'like' ? 'fill-current text-primary' : 'text-muted-foreground'}"
							/>
						</span>
					</Button>
					<Button
						variant="ghost"
						size="icon-sm"
						class="hidden lg:inline-flex"
						onclick={() => {
							const now = playback.now!;
							openAddToPlaylist({
								video_id: now.videoId,
								title: now.title,
								artists: now.artists,
								artist_id: now.artistId,
								thumbnail: now.thumbnail,
								duration: now.duration
							});
						}}
						aria-label="Add to playlist"
					>
						<HugeiconsIcon icon={Add01Icon} class="h-4 w-4 text-muted-foreground" />
					</Button>
				{/if}
				{#if currentSong}
					<TrackMenu
						song={currentSong}
						linksOnly
						onAdd={() => openAddToPlaylist(currentSong!)}
						triggerClass="inline-flex size-8 cursor-pointer items-center justify-center rounded-md text-muted-foreground transition hover:bg-muted hover:text-foreground"
					/>
				{/if}
			</div>
		{/if}
	</div>

	<!-- Transport -->
	<div class="flex flex-[1.5] flex-col items-center gap-1">
		<div class="flex items-center gap-1">
			<Button
				variant="ghost"
				size="icon-sm"
				onclick={() => api.toggleShuffle()}
				aria-label="Shuffle"
				aria-pressed={shuffleOn}
			>
				<HugeiconsIcon
					icon={ShuffleIcon}
					class="h-4 w-4 {shuffleOn ? 'text-primary' : 'text-muted-foreground'}"
				/>
			</Button>
			<Button variant="ghost" size="icon-sm" onclick={() => api.prevTrack()} aria-label="Previous">
				<HugeiconsIcon icon={PreviousIcon} class="h-5 w-5" />
			</Button>
			<Button
				variant="default"
				size="icon"
				class="rounded-full"
				onclick={() => api.togglePause()}
				aria-label="Play/pause"
			>
				<!-- HugeiconsIcon only re-renders `altIcon`/`showAlt`, not `icon` (frozen at mount) —
			     so toggle via showAlt, not a ternary on `icon`. -->
			<HugeiconsIcon
				icon={PauseIcon}
				altIcon={PlayIcon}
				showAlt={playback.paused}
				class="h-5 w-5"
			/>
			</Button>
			<Button variant="ghost" size="icon-sm" onclick={() => api.nextTrack()} aria-label="Next">
				<HugeiconsIcon icon={NextIcon} class="h-5 w-5" />
			</Button>
			<Button
				variant="ghost"
				size="icon-sm"
				onclick={cycleRepeat}
				aria-label="Repeat: {repeat}"
				aria-pressed={repeat !== 'off'}
			>
				<!-- icon swap via altIcon/showAlt — `icon` is frozen at mount (see play/pause above) -->
				<HugeiconsIcon
					icon={RepeatIcon}
					altIcon={RepeatOne01Icon}
					showAlt={repeat === 'one'}
					class="h-4 w-4 {repeat !== 'off' ? 'text-primary' : 'text-muted-foreground'}"
				/>
			</Button>
		</div>
		<div class="flex w-full max-w-md items-center gap-2 text-xs text-muted-foreground">
			<span class="tabular-nums">{fmt(shownPosition)}</span>
			<input
				type="range"
				class="range flex-1"
				style="--pct:{playback.duration ? (shownPosition / playback.duration) * 100 : 0}%"
				min="0"
				max={playback.duration || 0}
				value={shownPosition}
				oninput={onSeekInput}
				onchange={onSeekCommit}
				aria-label="Seek"
			/>
			<span class="tabular-nums">{fmt(playback.duration)}</span>
		</div>
	</div>

	<!-- Volume + queue -->
	<div class="flex flex-1 items-center justify-end gap-2">
		<!-- Volume is the first control to drop on a narrow window (OS volume still works). -->
		<div class="hidden items-center gap-1 md:flex">
			<Button
				variant="ghost"
				size="icon-sm"
				class="text-muted-foreground"
				onclick={toggleMute}
				aria-label={playback.volume === 0 ? 'Unmute' : 'Mute'}
			>
				<!-- icon swap via altIcon/showAlt — `icon` is frozen at mount (see play/pause above) -->
				<HugeiconsIcon
					icon={VolumeHighIcon}
					altIcon={VolumeMute02Icon}
					showAlt={playback.volume === 0}
					class="h-4 w-4"
				/>
			</Button>
			<input
				type="range"
				class="range w-24"
				style="--pct:{playback.volume}%"
				min="0"
				max="100"
				value={playback.volume}
				oninput={onVolume}
				onchange={onVolumeCommit}
				aria-label="Volume"
			/>
		</div>
		<!-- One cluster, so they sit tighter to each other than to the volume slider. -->
		<div class="flex items-center gap-0.5">
			<Button variant="ghost" size="icon-sm" onclick={openMiniPlayer} aria-label="Mini player">
				<HugeiconsIcon icon={MinimizeScreenIcon} class="h-5 w-5" />
			</Button>
			<Button
				variant={lyricsOpen ? 'secondary' : 'ghost'}
				size="icon-sm"
				onclick={onToggleLyrics}
				aria-label="Toggle lyrics"
			>
				<HugeiconsIcon icon={Mic01Icon} class="h-5 w-5" />
			</Button>
			<Button
				variant={queueOpen ? 'secondary' : 'ghost'}
				size="icon-sm"
				onclick={onToggleQueue}
				aria-label="Toggle queue"
			>
				<HugeiconsIcon icon={Queue01Icon} class="h-5 w-5" />
			</Button>
			<!-- The keyboard (and discoverable) way in and out of the now-playing view; clicking the
			     bar's empty space does the same thing. -->
			<Button
				variant="ghost"
				size="icon-sm"
				onclick={() => (np.open = !np.open)}
				aria-label={np.open ? 'Minimise player' : 'Open player'}
				aria-expanded={np.open}
			>
				<!-- icon swap via altIcon/showAlt — `icon` is frozen at mount (see play/pause above) -->
				<HugeiconsIcon
					icon={ArrowUp01Icon}
					altIcon={ArrowDown01Icon}
					showAlt={np.open}
					class="h-5 w-5"
				/>
			</Button>
		</div>
	</div>
</footer>
{/if}
