// frontend/src/components/QueuePanel.tsx
import React from 'react';
import { QueueList } from '../features/player/components/QueueList';

interface Props {
  onClose: () => void;
}

export const QueuePanel: React.FC<Props> = ({ onClose }) => (
  <>
    <button
      className="fixed inset-0 z-20 cursor-default bg-black/40 lg:hidden"
      onClick={onClose}
      aria-label="Close queue"
    />
    <aside className="absolute inset-y-0 right-0 z-30 flex h-full w-80 max-w-[80vw] flex-col border-l bg-card shadow-2xl animate-in slide-in-from-right duration-200">
      <h2 className="border-b px-4 py-3 font-heading text-sm font-semibold">Queue</h2>
      <QueueList />
    </aside>
  </>
);

// ui/src/lib/components/QueuePanel.svelte
<script lang="ts">
	import { fade, fly } from 'svelte/transition';
	import { cubicOut } from 'svelte/easing';
	import QueueList from './QueueList.svelte';

	let { onClose }: { onClose: () => void } = $props();
</script>

<!-- The panel always floats over the content (see the `relative` wrapper in +layout) rather than
     squeezing it into a column: two docked panels left the page too narrow to read, and a page you
     can't use behind a panel you opened on purpose is the better trade. Below lg a scrim dismisses
     it; at lg+ the content stays visible underneath and the player bar's button closes it. -->
<button
	class="absolute inset-0 z-20 cursor-default bg-black/40 lg:hidden"
	onclick={onClose}
	aria-label="Close queue"
	transition:fade={{ duration: 150 }}
></button>
<aside
	transition:fly={{ x: 32, duration: 220, easing: cubicOut }}
	class="absolute inset-y-0 right-0 z-30 flex h-full w-80 max-w-[80vw] flex-col border-l bg-card shadow-2xl"
>
	<h2 class="border-b px-4 py-3 font-heading text-sm font-semibold">Queue</h2>
	<QueueList />
</aside>
