// frontend/src/components/SavedInPlaylists.tsx
import { useState, useRef, useEffect } from 'react';
import { CheckCircle } from 'lucide-react';
import { BrowseItem } from '../lib/api';
import { thumb } from '../lib/thumb';

interface SavedInPlaylistsProps {
  playlists: BrowseItem[];
}

const SHOWN = 3;

/**
 * The "saved" mark on a track row: this song is already in one or more of your own playlists.
 * Pointing at it names them (three at most, "and N more" for the rest), and each one links
 * through to that playlist.
 */
export function SavedInPlaylists({ playlists }: SavedInPlaylistsProps) {
  const [open, setOpen] = useState(false);
  const [position, setPosition] = useState({ right: 0, top: 0, openUp: false });
  const triggerRef = useRef<HTMLButtonElement>(null);
  const closeTimeoutRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  const shown = playlists.slice(0, SHOWN);
  const extra = playlists.length - shown.length;

  const label =
    playlists.length === 1
      ? `Saved in ${playlists[0].title}`
      : `Saved in ${playlists.length} playlists`;

  const calculatePosition = () => {
    if (!triggerRef.current) return;
    const rect = triggerRef.current.getBoundingClientRect();
    const menuHeight = 44 + shown.length * 40;
    const openUp = rect.bottom + menuHeight > window.innerHeight;
    
    setPosition({
      right: window.innerWidth - rect.right,
      top: openUp ? window.innerHeight - rect.top : rect.bottom,
      openUp,
    });
  };

  const show = () => {
    if (closeTimeoutRef.current) {
      clearTimeout(closeTimeoutRef.current);
    }
    calculatePosition();
    setOpen(true);
  };

  const hide = () => {
    closeTimeoutRef.current = setTimeout(() => setOpen(false), 140);
  };

  const keep = () => {
    if (closeTimeoutRef.current) {
      clearTimeout(closeTimeoutRef.current);
    }
  };

  useEffect(() => {
    return () => {
      if (closeTimeoutRef.current) {
        clearTimeout(closeTimeoutRef.current);
      }
    };
  }, []);

  return (
    <>
      <button
        ref={triggerRef}
        className="cursor-pointer rounded-md p-1.5 text-primary transition hover:bg-accent/20"
        aria-label={label}
        title={label}
        onMouseEnter={show}
        onMouseLeave={hide}
        onFocus={show}
        onBlur={hide}
        onClick={(e) => e.stopPropagation()}
      >
        <CheckCircle className="h-4 w-4" />
      </button>

      {open && (
        <div
          className={`fixed z-50 min-w-52 max-w-72 animate-in rounded-lg border bg-popover p-1 text-popover-foreground shadow-xl duration-150 fade-in-0 zoom-in-95 ${
            position.openUp ? 'origin-bottom-right' : 'origin-top-right'
          }`}
          style={{
            right: `${position.right}px`,
            [position.openUp ? 'bottom' : 'top']: `${position.top}px`,
          }}
          onMouseEnter={keep}
          onMouseLeave={hide}
          role="tooltip"
        >
          <p className="px-2 pb-1 pt-1.5 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
            Saved in
          </p>
          {shown.map((pl) => (
            <a
              key={pl.id}
              href={`/playlist/${pl.id}`}
              className="flex w-full items-center gap-2 rounded-md p-1.5 hover:bg-accent/10"
              onClick={() => setOpen(false)}
            >
              {pl.thumbnail ? (
                <img src={thumb(pl.thumbnail, 96)} alt="" className="h-7 w-7 shrink-0 rounded object-cover" />
              ) : (
                <div className="h-7 w-7 shrink-0 rounded bg-muted"></div>
              )}
              <span className="min-w-0 truncate text-sm">{pl.title}</span>
            </a>
          ))}
          {extra > 0 && (
            <p className="px-2 pb-1 pt-0.5 text-xs text-muted-foreground">and {extra} more</p>
          )}
        </div>
      )}
    </>
  );
}

// ui/src/lib/components/SavedInPlaylists.svelte
<script lang="ts">
	// The "saved" mark on a track row: this song is already in one or more of your own playlists.
	// Pointing at it names them (three at most, "and N more" for the rest), and each one links
	// through to that playlist. The popup is `fixed`, anchored at the trigger and moved to <body>
	// (`toBody`), same as TrackMenu: a track list scrolls, and half of them are paint-contained.
	// Living at <body> is also why the links need no stopPropagation, despite the whole row being a
	// play target: nothing in there bubbles through the row any more.
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import { CheckmarkCircle03Icon } from '@hugeicons/core-free-icons';
	import type { BrowseItem } from '$lib/api';
	import { hrefFor } from '$lib/browse';
	import { anchorMenu, toBody } from '$lib/menu';

	let { playlists }: { playlists: BrowseItem[] } = $props();

	const SHOWN = 3;
	const shown = $derived(playlists.slice(0, SHOWN));
	const extra = $derived(playlists.length - shown.length);

	let open = $state(false);
	let mx = $state(0);
	let my = $state(0);
	let openUp = $state(false);
	// Crossing the gap between the mark and the popup is a mouseleave with nothing under the
	// pointer, so closing waits long enough for the next mouseenter to cancel it.
	let closing: ReturnType<typeof setTimeout> | undefined;

	function show(e: Event) {
		clearTimeout(closing);
		const trigger = e.currentTarget as HTMLElement;
		({ right: mx, y: my, openUp } = anchorMenu(trigger, 44 + shown.length * 40));
		open = true;
	}
	function hide() {
		clearTimeout(closing);
		closing = setTimeout(() => (open = false), 140);
	}
	function keep() {
		clearTimeout(closing);
	}

	const label = $derived(
		playlists.length === 1
			? `Saved in ${playlists[0].title}`
			: `Saved in ${playlists.length} playlists`
	);
</script>

<!-- Opens on hover and on focus, so it is reachable by tab as well as by pointer. The click does
     nothing but stay out of the row's way: toggling here would close the popup under a pointer
     that never left the mark. -->
<button
	class="cursor-pointer rounded-md p-1.5 text-primary transition hover:bg-accent/20"
	aria-label={label}
	title={label}
	onmouseenter={show}
	onmouseleave={hide}
	onfocus={show}
	onblur={hide}
	onclick={(e) => e.stopPropagation()}
>
	<HugeiconsIcon icon={CheckmarkCircle03Icon} class="h-4 w-4" />
</button>

{#if open}
	<div
		class="fixed z-50 min-w-52 max-w-72 animate-in rounded-lg border bg-popover p-1 text-popover-foreground shadow-xl duration-150 fade-in-0 zoom-in-95 {openUp
			? 'origin-bottom-right'
			: 'origin-top-right'}"
		style="right:{mx}px; {openUp ? 'bottom' : 'top'}:{my}px;"
		onmouseenter={keep}
		onmouseleave={hide}
		role="tooltip"
		{@attach toBody}
	>
		<p class="px-2 pb-1 pt-1.5 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
			Saved in
		</p>
		{#each shown as pl (pl.id)}
			<a
				href={hrefFor(pl)}
				class="flex w-full items-center gap-2 rounded-md p-1.5 hover:bg-accent/10"
				onclick={() => (open = false)}
			>
				{#if pl.thumbnail}
					<img src={pl.thumbnail} alt="" class="h-7 w-7 shrink-0 rounded object-cover" />
				{:else}
					<div class="h-7 w-7 shrink-0 rounded bg-muted"></div>
				{/if}
				<span class="min-w-0 truncate text-sm">{pl.title}</span>
			</a>
		{/each}
		{#if extra > 0}
			<p class="px-2 pb-1 pt-0.5 text-xs text-muted-foreground">and {extra} more</p>
		{/if}
	</div>
{/if}
