// frontend/src/components/TrackFilter.tsx
import { Search, X } from 'lucide-react';
import { SongItem } from '../lib/api';

interface TrackFilterProps {
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
}

/**
 * Filter box for a track list (playlist / album header).
 * Purely client-side, over the rows already loaded.
 */
export function TrackFilter({ value, onChange, placeholder = 'Search this list' }: TrackFilterProps) {
  return (
    <div className="flex items-center gap-2 rounded-full border bg-background/80 py-1.5 pl-3 pr-2 shadow-sm backdrop-blur focus-within:border-accent">
      <Search strokeWidth={2.5} className="h-4 w-4 shrink-0 text-muted-foreground" />
      <input
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        aria-label={placeholder}
        className="w-48 min-w-0 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
        onKeyDown={(e) => e.key === 'Escape' && onChange('')}
      />
      {/* Holds its 1rem either way, so typing doesn't resize the box. */}
      <button
        className={`w-4 shrink-0 cursor-pointer text-muted-foreground transition hover:text-foreground ${
          !value ? 'invisible' : ''
        }`}
        onClick={() => onChange('')}
        aria-label="Clear search"
        tabIndex={value ? 0 : -1}
      >
        <X strokeWidth={2.5} className="h-4 w-4" />
      </button>
    </div>
  );
}

/** Substring match over title, artist and album. Empty query returns the list untouched. */
export function filterTracks<T extends SongItem>(items: T[], query: string): T[] {
  const q = query.trim().toLowerCase();
  if (!q) return items;
  return items.filter(
    (t) =>
      t.title?.toLowerCase().includes(q) ||
      t.artists?.toLowerCase().includes(q) ||
      t.album?.toLowerCase().includes(q)
  );
}

// ui/src/lib/components/TrackFilter.svelte
<!--
	Filter box for a track list (playlist / album header).

	Purely client-side, over the rows already loaded. A long playlist arrives a page at a time, so
	the pages the sentinel hasn't fetched yet can't match; scrolling loads them as usual.
-->
<script module lang="ts">
	import type { SongItem } from '$lib/api';

	/** Substring match over title, artist and album. Empty query returns the list untouched. */
	export function filterTracks<T extends SongItem>(items: T[], query: string): T[] {
		const q = query.trim().toLowerCase();
		if (!q) return items;
		return items.filter(
			(t) =>
				t.title?.toLowerCase().includes(q) ||
				t.artists?.toLowerCase().includes(q) ||
				t.album?.toLowerCase().includes(q)
		);
	}
</script>

<script lang="ts">
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import { SearchList01Icon, Cancel01Icon } from '@hugeicons/core-free-icons';

	let {
		value = $bindable(''),
		placeholder = 'Search this list'
	}: { value?: string; placeholder?: string } = $props();
</script>

<div
	class="flex items-center gap-2 rounded-full border bg-background/80 py-1.5 pl-3 pr-2 shadow-sm backdrop-blur focus-within:border-accent"
>
	<HugeiconsIcon
		icon={SearchList01Icon}
		strokeWidth={2.5}
		class="h-4 w-4 shrink-0 text-muted-foreground"
	/>
	<input
		bind:value
		{placeholder}
		aria-label={placeholder}
		class="w-48 min-w-0 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
		onkeydown={(e) => e.key === 'Escape' && (value = '')}
	/>
	<!-- Holds its 1rem either way, so typing doesn't resize the box. -->
	<button
		class="w-4 shrink-0 cursor-pointer text-muted-foreground transition hover:text-foreground"
		class:invisible={!value}
		onclick={() => (value = '')}
		aria-label="Clear search"
		tabindex={value ? 0 : -1}
	>
		<HugeiconsIcon icon={Cancel01Icon} strokeWidth={2.5} class="h-4 w-4" />
	</button>
</div>
