// frontend/src/components/TrackMenu.tsx
import React, { useState, useRef } from 'react';
import {
  MoreHorizontal, ArrowUpNarrowWide, ArrowDownWideNarrow,
  Radio, ThumbsUp, ThumbsDown, User, Disc3, LayoutDashboard, Share2,
  ListPlus, ListMinus, Settings2,
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import type { SongItem } from '../lib/api';
import { isLocalId } from '../lib/api';
import { anchorMenu } from '../lib/menu';
import { cn } from '../lib/utils';
import { usePlayer } from '../features/player/PlayerContext';
import { usePersonal } from '../features/home/PersonalContext';

interface Props {
  song: SongItem;
  triggerClass?: string;
  onAdd?: () => void;
  onRemove?: () => void;
  removeLabel?: string;
  linksOnly?: boolean;
}

export const TrackMenu: React.FC<Props> = ({
  song, triggerClass = '', onAdd, onRemove, removeLabel = 'Remove from playlist', linksOnly = false,
}) => {
  const navigate = useNavigate();
  const { playNext, addToQueue, startRadio, toggleRating, ratingOf } = usePlayer();
  const { addPick } = usePersonal();
  const [open, setOpen] = useState(false);
  const [pos, setPos] = useState({ right: 0, y: 0, openUp: false });
  const triggerRef = useRef<HTMLButtonElement>(null);
  const isLocal = isLocalId(song.video_id);
  const rated = ratingOf(song);

  function openMenu(e: React.MouseEvent) {
    e.stopPropagation();
    if (triggerRef.current) {
      const anchor = anchorMenu(triggerRef.current);
      setPos(anchor);
    }
    setOpen(true);
  }

  function run(e: React.MouseEvent, action?: () => void) {
    e.stopPropagation();
    setOpen(false);
    action?.();
  }

  return (
    <>
      <button
        ref={triggerRef}
        className={cn(triggerClass, open && 'opacity-100')}
        onClick={openMenu}
        aria-label="Track options"
      >
        <MoreHorizontal className="h-4 w-4" />
      </button>

      {open && (
        <>
          <button
            className="fixed inset-0 z-40 cursor-default"
            onClick={(e) => { e.stopPropagation(); setOpen(false); }}
            aria-label="Close menu"
          />
          <div
            className={cn(
              'fixed z-50 min-w-44 rounded-lg border bg-popover p-1 text-popover-foreground shadow-xl',
              'animate-in fade-in-0 zoom-in-95 duration-150',
              pos.openUp ? 'origin-bottom-right' : 'origin-top-right',
            )}
            style={{ right: pos.right, [pos.openUp ? 'bottom' : 'top']: pos.y }}
          >
            {!linksOnly && (
              <>
                <button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
                  onClick={(e) => run(e, () => playNext([song], song.title))}>
                  <ArrowUpNarrowWide className="h-4 w-4" /> Play next
                </button>
                <button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
                  onClick={(e) => run(e, () => addToQueue([song], song.title))}>
                  <ArrowDownWideNarrow className="h-4 w-4" /> Add to queue
                </button>
              </>
            )}
            {!isLocal && (
              <button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
                onClick={(e) => run(e, () => startRadio('song', song.video_id, song.title))}>
                <Radio className="h-4 w-4" /> Start radio
              </button>
            )}
            {!isLocal && (
              <>
                <button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
                  onClick={(e) => run(e, () => toggleRating(song, 'like'))}>
                  <ThumbsUp className={cn('h-4 w-4', rated === 'like' && 'fill-current text-primary')} />
                  {rated === 'like' ? 'Remove from Liked Songs' : 'Save to Liked Songs'}
                </button>
                <button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
                  onClick={(e) => run(e, () => toggleRating(song, 'dislike'))}>
                  <ThumbsDown className={cn('h-4 w-4', rated === 'dislike' && 'fill-current')} />
                  {rated === 'dislike' ? 'Remove dislike' : 'Dislike'}
                </button>
              </>
            )}
            {song.artist_id && (
              <button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
                onClick={(e) => run(e, () => navigate(`/artist/${encodeURIComponent(song.artist_id!)}`) )}>
                <User className="h-4 w-4" /> Go to artist
              </button>
            )}
            {song.album_id && !isLocal && (
              <button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
                onClick={(e) => run(e, () => navigate(`/album/${encodeURIComponent(song.album_id!)}`) )}>
                <Disc3 className="h-4 w-4" /> Go to album
              </button>
            )}
            <button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
              onClick={(e) => run(e, () => addPick({ kind: 'song', id: song.video_id, title: song.title, subtitle: song.artists, thumbnail: song.thumbnail }))}>
              <LayoutDashboard className="h-4 w-4" /> Add to shortcuts
            </button>
            {onAdd && !isLocal && (
              <button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
                onClick={(e) => run(e, onAdd)}>
                <ListPlus className="h-4 w-4" /> Add to playlist
              </button>
            )}
            {onRemove && (
              <button className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm text-destructive hover:bg-destructive/10"
                onClick={(e) => run(e, onRemove)}>
                <ListMinus className="h-4 w-4" /> {removeLabel}
              </button>
            )}
          </div>
        </>
      )}
    </>
  );
};

// ui/src/lib/components/TrackMenu.svelte
<script lang="ts">
	// The ⋯ options menu shared by TrackRow (inline trigger) and MediaCard (overlay trigger).
	// The queue actions + like are universal; go-to-artist/album/playlist show when the song carries
	// them. The popup is `fixed`, anchored at the trigger and moved to <body> (`toBody`), so no
	// scroll container clips it and no contained ancestor becomes its containing block.
	import { goto } from '$app/navigation';
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import {
		MoreHorizontalIcon,
		MoreVerticalIcon,
		PlayListAddIcon,
		PlayListRemoveIcon,
		ArrowUpNarrowWideIcon,
		ArrowDownWideNarrowIcon,
		Radio02Icon,
		ThumbsUpIcon,
		ThumbsDownIcon,
		UserListIcon,
		Vynil02Icon,
		DashboardSquare02Icon,
		Share08Icon,
		PreferenceVerticalIcon
	} from '@hugeicons/core-free-icons';
	import * as api from '$lib/api';
	import type { SongItem } from '$lib/api';
	import { anchorMenu, toBody } from '$lib/menu';
	import { addPick, enqueue, openShare, ratingOf, startRadio, toggleRating } from '$lib/player.svelte';
	import TempoPitchDialog from './TempoPitchDialog.svelte';

	let {
		song,
		triggerClass = '',
		onAdd,
		onRemove,
		removeLabel = 'Remove from playlist',
		linksOnly = false
	}: {
		song: SongItem;
		/** Classes for the ⋯ trigger button (positioning differs per host: inline vs overlay). */
		triggerClass?: string;
		/** Adds an "Add to playlist" menu item. */
		onAdd?: () => void;
		/** Adds a remove menu item (label via `removeLabel`). */
		onRemove?: () => void;
		removeLabel?: string;
		/** Player-bar variant: ⋮ trigger, and only artist/album/shortcuts (queue and like already
		    have their own buttons there). */
		linksOnly?: boolean;
	} = $props();

	let menuOpen = $state(false);
	// Player-bar only: tempo/pitch belong to playback, not to a row you happen to be pointing at.
	let advancedOpen = $state(false);
	let mx = $state(0);
	let my = $state(0);
	let openUp = $state(false);

	function openMenu(e: MouseEvent) {
		e.stopPropagation();
		({ right: mx, y: my, openUp } = anchorMenu(e.currentTarget as HTMLElement));
		menuOpen = true;
	}
	// stopPropagation everywhere: the trigger sits inside a clickable row (TrackRow's whole row is a
	// play target), so its click must not reach the row's onplay (e.g. replacing the queue with the
	// playlist). The popup itself now lives at <body> and no longer bubbles into the row, but these
	// stay: they cost nothing and the trigger still needs them.
	function run(e: MouseEvent, action?: () => void) {
		e.stopPropagation();
		menuOpen = false;
		action?.();
	}
	function close(e: MouseEvent) {
		e.stopPropagation();
		menuOpen = false;
	}

	const rated = $derived(ratingOf(song));
	// A local file has no YouTube identity: liking it or putting it in a YTM playlist is not a
	// thing, so those items don't show. Queue, shortcuts and go-to-album work normally.
	const isLocal = $derived(api.isLocalId(song.video_id));
</script>

<button class="{triggerClass} {menuOpen ? 'opacity-100' : ''}" onclick={openMenu} aria-label="Track options">
	<!-- icon swap via altIcon/showAlt — `icon` is frozen at mount -->
	<HugeiconsIcon
		icon={MoreHorizontalIcon}
		altIcon={MoreVerticalIcon}
		showAlt={linksOnly}
		class="h-4 w-4"
	/>
</button>

{#if menuOpen}
	<button
		class="fixed inset-0 z-40 cursor-default"
		onclick={close}
		aria-label="Close menu"
		{@attach toBody}
	></button>
	<div
		class="fixed z-50 min-w-44 animate-in rounded-lg border bg-popover p-1 text-popover-foreground shadow-xl duration-150 fade-in-0 zoom-in-95 {openUp
			? 'origin-bottom-right'
			: 'origin-top-right'}"
		style="right:{mx}px; {openUp ? 'bottom' : 'top'}:{my}px;"
		{@attach toBody}
	>
		{#if !linksOnly}
			<button
				class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
				onclick={(e) => run(e, () => enqueue([song], true))}
			>
				<HugeiconsIcon icon={ArrowUpNarrowWideIcon} class="h-4 w-4" /> Play next
			</button>
			<button
				class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
				onclick={(e) => run(e, () => enqueue([song], false))}
			>
				<HugeiconsIcon icon={ArrowDownWideNarrowIcon} class="h-4 w-4" /> Add to queue
			</button>
		{/if}
		<!-- Radio is the one action worth having in the player bar too (`linksOnly`): it's how you
		     say "keep going with more like this" about the song that's playing. -->
		{#if !isLocal}
			<button
				class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
				onclick={(e) => run(e, () => startRadio('song', song.video_id, song.title))}
			>
				<HugeiconsIcon icon={Radio02Icon} class="h-4 w-4" /> Start radio
			</button>
		{/if}
		<!-- In the player bar (`linksOnly`) like and add-to-playlist have their own buttons, but those
		     drop below lg to leave the title room, so the menu carries them at that width instead.
		     Dislike has no button of its own anywhere, so it stays visible at every width. -->
		{#if !isLocal}
			<button
				class="w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10 {linksOnly
					? 'flex lg:hidden'
					: 'flex'}"
				onclick={(e) => run(e, () => toggleRating(song, 'like'))}
			>
				<HugeiconsIcon
					icon={ThumbsUpIcon}
					class="h-4 w-4 {rated === 'like' ? 'fill-current text-primary' : ''}"
				/>
				{rated === 'like' ? 'Remove from Liked Songs' : 'Save to Liked Songs'}
			</button>
			<button
				class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
				onclick={(e) => run(e, () => toggleRating(song, 'dislike'))}
			>
				<HugeiconsIcon
					icon={ThumbsDownIcon}
					class="h-4 w-4 {rated === 'dislike' ? 'fill-current text-foreground' : ''}"
				/>
				{rated === 'dislike' ? 'Remove dislike' : 'Dislike'}
			</button>
		{/if}
		{#if song.artist_id}
			<button
				class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
				onclick={(e) => run(e, () => goto(`/artist/${encodeURIComponent(song.artist_id!)}`))}
			>
				<HugeiconsIcon icon={UserListIcon} class="h-4 w-4" /> Go to artist
			</button>
		{/if}
		<!-- Local files carry no album_id (local.rs). Checked here too: a queue restored from before
		     that changed still has one on its rows, and it would open a page this menu shouldn't offer. -->
		{#if song.album_id && !isLocal}
			<button
				class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
				onclick={(e) => run(e, () => goto(`/album/${encodeURIComponent(song.album_id!)}`))}
			>
				<HugeiconsIcon icon={Vynil02Icon} class="h-4 w-4" /> Go to album
			</button>
		{/if}
		<button
			class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
			onclick={(e) =>
				run(e, () =>
					addPick({
						kind: 'song',
						id: song.video_id,
						title: song.title,
						subtitle: song.artists,
						thumbnail: song.thumbnail
					})
				)}
		>
			<HugeiconsIcon icon={DashboardSquare02Icon} class="h-4 w-4" /> Add to shortcuts
		</button>
		{#if !isLocal}
			<button
				class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
				onclick={(e) =>
					run(e, () =>
						openShare({
							kind: 'song',
							id: song.video_id,
							title: song.title,
							subtitle: song.artists,
							thumbnail: song.thumbnail
						})
					)}
			>
				<HugeiconsIcon icon={Share08Icon} class="h-4 w-4" /> Share
			</button>
		{/if}
		{#if linksOnly}
			<button
				class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10"
				onclick={(e) => run(e, () => (advancedOpen = true))}
			>
				<HugeiconsIcon icon={PreferenceVerticalIcon} class="h-4 w-4" /> Advanced
			</button>
		{/if}
		{#if onAdd && !isLocal}
			<button
				class="w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-accent/10 {linksOnly
					? 'flex lg:hidden'
					: 'flex'}"
				onclick={(e) => run(e, onAdd)}
			>
				<HugeiconsIcon icon={PlayListAddIcon} class="h-4 w-4" /> Add to playlist
			</button>
		{/if}
		{#if onRemove}
			<button
				class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm text-destructive hover:bg-destructive/10"
				onclick={(e) => run(e, onRemove)}
			>
				<HugeiconsIcon icon={PlayListRemoveIcon} class="h-4 w-4" /> {removeLabel}
			</button>
		{/if}
	</div>
{/if}

{#if linksOnly}
	<TempoPitchDialog bind:open={advancedOpen} />
{/if}
